### ISSUE TITLE
What's the support for matrices?

### ISSUE THREAD

**Issue by PeterBocan** [Khan/KaTeX#195] opened 2015-03-05 16:45 UTC
Hello guys, I wonder what's the current support for matrices in KaTeX? Haven't seen a word about it (maybe I was looking at wrong place).

**Comment by xymostech** [comment] 2015-03-05 22:19
There is currently no support for it, but it's on the list of things to work on. Duplicate of #43

**Closed by xymostech** 2015-03-05 22:19 UTC
