### ISSUE TITLE
Support other mathematical fonts

### ISSUE THREAD

**Issue by kasperpeulen** [Khan/KaTeX#555] opened 2016-10-30 16:46 UTC
Support other mathematical fonts. There are a couple of fonts with a MATH table:
- Asana Math
- Cambria Math
- DejaVu Math TeX Gyre
- Latin Modern Math
- Libertinus Math
- Lucida Bright Math
- Minion Math
- STIX Math
- TeX Gyre Bonum Math
- TeX Gyre Pagella Math
- TeX Gyre Schola Math
- TeX Gyre Termes Math
- XITS Math

One thing I like about Latin Modern Roman is that the font-weight is a lot finer. Which makes it look more elegant. Alternatively, it would be helpful if you could set the font-weight of the default KaTeX font.

**Comment by kasperpeulen** [comment] 2016-10-30 16:52
For a visual comparison:

KaTeX Font:
![image](https://cloud.githubusercontent.com/assets/1035299/19838147/62186386-9ec9-11e6-8bfc-61bae743cf8e.png)

Latin Modern Roman font:
![image](https://cloud.githubusercontent.com/assets/1035299/19838155/768d8512-9ec9-11e6-95df-036439c2bf21.png)

**Comment by kevinbarabash** [comment] 2016-10-30 18:16
Duplicate of https://github.com/Khan/KaTeX/issues/123.

**Closed by kevinbarabash** 2016-10-30 18:16 UTC
