### ISSUE TITLE
incorrect spacing of operators when combining fonts and sub-/sup-scripts

### ISSUE THREAD

**Issue by ccreus** [Khan/KaTeX#424] opened 2015-12-31 11:09 UTC
The spacing to the right of + is wrong with an expression like: 
a+\mathtt{a}_1
The spacing is correct when either \mathtt or _1 is omitted.

This behavior also occurs when:
- using \mathit, \mathsf, etc., instead of \mathtt
- using a superscript ^1 instead of the subscript _1
- changing + by other operators with some spacing to their right, like >, \leq, \mid, etc.

**Comment by kevinbarabash** [comment] 2015-12-31 18:24
Thanks for the bug report.  I've verified the issue, but I'm not sure what's causing it.

**Comment by kohler** [comment] 2016-11-27 17:40
This is a duplicate of #534.

**Closed** 2016-12-08 01:02 UTC
Labels: bug
