### ISSUE TITLE
\mathrlap bounding box does not expand for tall argument

### ISSUE THREAD

**Issue by yeruoforever** [Khan/KaTeX#1153] opened 2018-02-12 13:43 UTC
when input this:
$$T+\rlap{\overbrace{\phantom{a_0+a_1+a_2+\cdots+a_k}}^m}a_0+\underbrace{a_1+a_2+\cdots+a_k}_n+f$$
output is :
![2018-02-12 21-33-40](https://user-images.githubusercontent.com/19868036/36099239-d167dfa6-103c-11e8-9282-0f5102d15416.png)
some times output is like this：
![2018-02-12 21-40-10](https://user-images.githubusercontent.com/19868036/36099476-ca06b4c0-103d-11e8-8ca0-1c7f59d3923b.png)
$$T+\rlap{\overbrace{\phantom{a_0+a_1+a_2+\cdots+a_k}}^m}a_0+\underbrace{a_1+a_2+\cdots+a_k}_n+f$
$$

**Comment by edemaine** [comment] 2018-02-12 16:44
FWIW, that code should be
```latex
T+\mathrlap{\overbrace{\phantom{a_0+a_1+a_2+\cdots+a_k}}^m}a_0+\underbrace{a_1+a_2+\cdots+a_k}_n+f
```
I confirm that I see the same as your first image, which is buggy.  (I couldn't get the example with `$` to work, even with `\$`.  But LaTeX renders it like your second image.)  My guess is that the height of the `\phantom` is somehow not getting incorporated into the height computation of the `\overbrace`... but this will require some investigation.

**Comment by ronkok** [comment] 2018-02-12 17:37
There is a bug there and I'll look into it. In the meantime, @yeruoforever , is this the sort of thing you were seeking?
![overbrace](https://user-images.githubusercontent.com/16403058/36110663-467b551c-0fd8-11e8-8030-76231879462f.PNG)


If so, then you can use:
```
$$ T+\overbrace{a_0+\underbrace{a_1+a_2+\cdots+a_k}_n}^m + f $$
```

**Comment by ronkok** [comment] 2018-02-12 19:26
I believe that I see the source of the bug. The problem is in `\rmathrlap`, not `\overbrace` or `\phantom`.

 KaTeX `rlap` and `llap` have always worked by just nesting a span with absolute positioning inside a span that has relative positioning. Then it is easy to manipulate the horizontal alignment by setting `left: 0;`  or `right:0;`.  

But that doesn't address the vertical alignment issues when tall math structures come into play. We need to incorporate a `makeVList` into the `\mathrlap` HTML handler.  

I can work something up in the next couple of days.

**Comment by edemaine** [comment] 2018-02-12 19:28
@ronkok Nice! So it's the HTML vertical bounding box being incorrect, not that the `height` value isn't getting set?

**Comment by ronkok** [comment] 2018-02-12 19:34
@edemaine Exactly correct. You can confirm that by erasing `\phantom` from the expression. All the vertical alignment issues are still there. On the other hand, if you erase `\mathrlap`, all the vertical alignment issues are resolved.

There probably many ways to fix this, but the KaTeX `makeVList` method has been debugged to overcome many browser-specific vertical alignment issues. It's the most reliable way to go.

**Comment by ronkok** [comment] 2018-02-14 18:54
This bug can be fixed in file `lap.js` by replacing line 39:
```
        return buildCommon.makeSpan(
            ["mord", group.value.alignment], [inner, fix], options);
```

... with this code:
```
        const node = buildCommon.makeSpan(
            ["mord", group.value.alignment], [inner, fix], options);

        // Use struts to vertically define the HTML bounding box.
        // See buildHTML.js for comments re: IE 9.
        const topStrut = buildCommon.makeSpan(["strut"]);
        const bottomStrut = buildCommon.makeSpan(["strut", "bottom"]);
        topStrut.style.height = node.height + "em";
        bottomStrut.style.height = (node.height + node.depth) + "em";
        bottomStrut.style.verticalAlign = -node.depth + "em";
        return buildCommon.makeSpan([], [topStrut, bottomStrut, node]);
```

As soon as I get my submodule issues worked out, I'll turn in a PR. But if this is a rush, anyone should feel free to do it sooner.

**Comment by yeruoforever** [comment] 2018-02-16 04:23
thanks very much

**Comment by edemaine** [comment] 2018-02-16 21:03
Leaving this open until the PR gets merged.

**Closed** 2018-05-25 01:28 UTC
Labels: bug
