### ISSUE TITLE
\underbrace and \overbrace should put their args into \displaystyle unconditionally

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#764] opened 2017-07-14 04:07 UTC
If there's a group that comes right after `\displaystyle` then we only apply its effects to that group instead of everything that follows `\displaystyle`.

```
\overbrace{
\displaystyle{\oint_S{\vec E\cdot\hat n\,\mathrm d a}}}^\text{emf} = 
\underbrace{\frac{q_{\text{enc}}}{\varepsilon_0}}_{\text{charge}}
```

![horizontalbraces](https://user-images.githubusercontent.com/1044413/28197956-5166b62c-6828-11e7-91ef-2af344aaeb09.png)
LaTeX is in green, KaTeX is in red.  Notice the size difference.

**Comment by kohler** [comment] 2017-07-14 18:37
Don't think this is a correct analysis. The `\displaystyle` is **inside** a group, the `\overbrace` group.

What really appears to be going on is that `\underbrace` and `\overbrace` should put their arguments into display mode unconditionally. TeX input

```
$
{{\oint_S{\vec E\cdot\hat n\,\mathrm d a}}} = 
{\frac{q_{\text{enc}}}{\varepsilon_0}}
$

$
\overbrace{{\oint_S{\vec E\cdot\hat n\,\mathrm d a}}} = 
\underbrace{\frac{q_{\text{enc}}}{\varepsilon_0}}
$
```

Image output

![screen shot 2017-07-14 at 2 35 41 pm](https://user-images.githubusercontent.com/410647/28225806-dd654a34-68a1-11e7-8c8e-2f482eb82e88.png)

**Comment by edemaine** [comment] 2017-07-14 21:19
`groupTypes.horizBrace` has the following code:

```javascript
    // Build the base group
    const body = buildGroup(
       group.value.base, options.havingStyle(style.cramp()));
```

I'm not sure what cramped means, but I'm guessing we want to in addition / instead switch `style` to its `display` version, with a new `display()` method on `Style`?

**Comment by ronkok** [comment] 2017-07-15 01:20
"Cramped" is a style modification in which exponents are not raised as high as they would be in in non-cramped style. "Cramped" is typically used in something like a fraction numerator or denominator, or in this case, a brace.

I reckon that you are correct in saying that a style adjustment is needed here. If you would like to suggest something more detailed, that would be welcome. Otherwise I'll get some time for research in a few days.

**Comment by kohler** [comment] 2017-07-15 18:18
Definition of `\over/underbrace` in LaTeX `fontmath.ltx`

```
\def\overbrace#1{\mathop{\vbox{\m@th\ialign{##\crcr\noalign{\kern3\p@}%
      \downbracefill\crcr\noalign{\kern3\p@\nointerlineskip}%
      $\hfil\displaystyle{#1}\hfil$\crcr}}}\limits}
\def\underbrace#1{\mathop{\vtop{\m@th\ialign{##\crcr
   $\hfil\displaystyle{#1}\hfil$\crcr
   \noalign{\kern3\p@\nointerlineskip}%
   \upbracefill\crcr\noalign{\kern3\p@}}}}\limits}
```

**Comment by edemaine** [comment] 2017-07-15 20:24
I'm a little confused about cramped style.  Does it correspond to something in LaTeX (perhaps defined in mathtools?) that you're reproducing?  I looked at mathtools's definition of `\over/underbrace` and didn't see anything about "cramped"...

```latex
\def\overbrace#1{\mathop{\vbox{\m@th\ialign{##\crcr
  \noalign{\kern.5\fontdimen5\textfont2}%
  \downbracefill\crcr
  \noalign{\kern.7\fontdimen5\textfont2\nointerlineskip}%
  $\hfil\displaystyle{#1}\hfil$\crcr}}}\limits}
```

Anyway, with the following change:

```diff
diff --git a/src/buildHTML.js b/src/buildHTML.js
index 944fdc6..d9d8e9a 100644
--- a/src/buildHTML.js
+++ b/src/buildHTML.js
@@ -1516,7 +1516,7 @@ groupTypes.horizBrace = function(group, options) {

     // Build the base group
     const body = buildGroup(
-       group.value.base, options.havingStyle(style.cramp()));
+       group.value.base, options.havingBaseStyle(Style.DISPLAY));

     // Create the stretchy element
     const braceBody = stretchy.svgSpan(group, options);
```

I get the following `texcmp` output for the HorizontalBraces test, which seems to be on the right track:

![horizontalbraces](https://user-images.githubusercontent.com/2218736/28242449-db19b3ea-6979-11e7-9a59-5fbeaab89a74.png)

**Comment by kevinbarabash** [comment] 2017-07-15 22:32
Looks great!

**Comment by edemaine** [comment] 2017-07-15 23:25
OK, #765 was merged, which switches the text being braced into displaystyle. This definitely seems in line with the LaTeX/mathtools source.

@ronkok In particular, I don't see why the main-line text would be cramped.  (I could see it for the above/below text...)  Do you agree?

**Closed by edemaine** 2017-07-15 23:25 UTC

**Comment by ronkok** [comment] 2017-07-15 23:47
I do agree.

**Comment by kohler** [comment] 2017-07-17 14:24
FYI TeX commands such as `\textstyle`/`\displaystyle` always reset the “cramped” flag to false.

**Comment by edemaine** [comment] 2017-07-17 15:30
Finally found "cramped" briefly mentioned on page 140 of the TeXbook.

> TEX actually has eight different styles in which it can treat formulas, namely
 display style (for formulas displayed on lines by themselves)
 text style (for formulas embedded in the text)
script style (for formulas used as superscripts or subscripts)
scriptscript style (for second-order superscripts or subscripts)
and four other “cramped” styles that are almost the same except that exponents aren’t raised quite so much. For brevity we shall refer to the eight styles as
D, D', T, T', S, S', SS, SS',
where D is display style, D' is cramped display style, T is text style, etc.

Looks like #765, which uses `options.havingBaseStyle(Style.DISPLAY)`, will indeed reset cramped to false.

**Comment by ronkok** [comment] 2017-07-17 18:46
Yep, that's "cramped". And KaTeX does use "cramped" to modify `sup` elevation when inside numerators, denominators, `\sqrt`, etc. It was an error on my part to use it inside `\overbrace`. I'm glad that others have straightened things out.
