### ISSUE TITLE
Testing in Jest

### ISSUE THREAD

**Issue by Rokt33r** [Khan/KaTeX#664] opened 2017-03-03 16:51 UTC
`document.compatMode = 'BackCompat'` is set on the environment of  [Jest](https://github.com/facebook/jest).

So, I always see this warning when testing with Jest.(I'm using `renderToString` function only.)
```
Warning: KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype.
```

It is quite annoying for me. Is there any way to ignore?

**Comment by pyramation** [comment] 2017-04-14 11:00
I'm only including the library without rendering a component in a test, and it still displays this warning in every single test. Can this `console.warn` just be removed, please?

**Comment by xymostech** [comment] 2017-04-14 22:00
Looks like @edemaine is dealing with the actual bug in jest, but I just wanted to chime in and say that a significant number of reports about KaTeX's rendering failed is caused by people not using a suitable doctype. So I'd be hesitant to remove it!

**Comment by Rokt33r** [comment] 2017-04-14 22:24
@xymostech I think just adding one option, like `ignoreCompatModeWarning (false by default)`, would fix this...

**Comment by edemaine** [comment] 2017-04-15 20:38
Adding a warning toggle seems reasonable; I can imagine various situations where the caller doesn't want console messages.  There are also the "No character metrics" warnings.  Would it make sense to have a global `warnings` setting that defaults to `true`, and use that?  If so, I can do a PR.

**Comment by kevinbarabash** [comment] 2017-04-16 01:14
@edemaine would setting the `warnings` option to false disable all error reporting?

**Comment by edemaine** [comment] 2017-04-16 03:25
@kevinbarabash That's what I was imagining... though I'm not sure exactly what's best here.  Presumably these tests are testing functionality other than KaTeX, so all KaTeX-related warnings would be annoying...

**Comment by edemaine** [comment] 2017-04-27 16:20
I realize a problem with my suggestion: the quirks mode test is currently done at the top level of `katex.js`, not when calling `render`.  That early, there wouldn't be an options object to check for a `warnings: false` setting.  What do you think about moving the warning into the first call to `render` (and maybe also `__parse`...?).

**Comment by edemaine** [comment] 2017-04-27 16:23
@Rokt33r @pyramation Would you be willing to try [this slightly tweaked version of Jest](https://github.com/edemaine/jest) to confirm that it removes the KaTeX warning?  I'm not very familiar with Jest, so it's tricky for me to actually test, but discussion on https://github.com/facebook/jest/issues/3299 suggests that this will fix it.

**Comment by Rokt33r** [comment] 2017-06-10 11:37
@edemaine 
How could I install this?

**Comment by edemaine** [comment] 2017-06-10 17:13
@Rokt33r `git clone git@github.com:edemaine/jest.git`

**Comment by kevinbarabash** [comment] 2017-07-31 02:45
@Rokt33r I just merged https://github.com/Khan/KaTeX/pull/608.  Can you verify that that solves this issue?

**Comment by Rokt33r** [comment] 2017-07-31 06:07
I actually have no idea how should I install the unpublished code. Should I clone and install it manually?

**Comment by kevinbarabash** [comment] 2017-07-31 13:58
@Rokt33r you'd have to clone the KaTeX repo and run `make build` and copy the built files to your project.

**Comment by Rokt33r** [comment] 2017-08-01 03:36
I've tried just now, but still got same warning.
<img width="1001" alt="screen shot 2017-08-01 at 12 32 18 pm" src="https://user-images.githubusercontent.com/5865853/28808326-f168d6dc-76b5-11e7-8c5b-312c8ee728e2.png">

**Comment by kevinbarabash** [comment] 2017-08-01 03:48
@Rokt33r thanks for trying.  I'm sorry, I forgot to mention that I rolled back the change change that removed the warning for quirks mode b/c the proposed fix didn't produce acceptable renderings.   The plan is to enable the fix for limited quirks mode while continuing to warn in full quirks mode.

**Comment by Rokt33r** [comment] 2017-08-01 07:52
I see. Now, I know how to do try. Just ping me again when you ready.

**Comment by kevinbarabash** [comment] 2017-09-15 12:33
It appears that @edemaine proposed change to jest has made its way onto jest/master (see https://github.com/facebook/jest/commit/fcf64d79a67a64192660d3a8821a68f3507d661e) so I think this can be closed.

**Comment by kevinbarabash** [comment] 2017-09-15 12:33
@Rokt33r please re-open if upgrading jest to `v21.1.0` or greater doesn't solve the issue.

**Closed by kevinbarabash** 2017-09-15 12:33 UTC

**Comment by tgrant59** [comment] 2017-10-26 20:04
@kevinbarabash I'm still seeing this waring on jest `v21.1.0`
