### ISSUE TITLE
Line breaks within container

### ISSUE THREAD

**Issue by mull** [Khan/KaTeX#464] opened 2016-04-27 07:19 UTC
Hey guys. My problem is that I'm trying, or hoping, to render math on mobile devices. We're looking at Katex as a much preferable alternative to Mathjax, as is everyone I guess. :-)

The obvious problem on mobile is line breaks. Our ideal situation is for math to line break as normal text would. This can be achieved with Mathjax, but seemingly not with Katex. Is there anything we can do about that?

JS-fiddle to demonstrate: https://jsfiddle.net/98bp26dw/2/

PS. I saw another issue related to creating manual line breaks, but it didn't seem to touch on the exact same subject.

**Comment by spicyj** [comment] 2016-04-28 04:26
(Duplicate of #327.)

**Closed by spicyj** 2016-04-28 04:26 UTC
