### ISSUE TITLE
Spacing of `10 \times` is incorrect.

### ISSUE THREAD

**Issue by WChargin** [Khan/KaTeX#355] opened 2015-09-13 19:17 UTC
![Image of `10 \times` in the KaTeX repl](https://cloud.githubusercontent.com/assets/4317806/9838376/2f42ea56-5a11-11e5-8482-738dbfe8334a.png)

```
$ pdftex <<< '\relax \nopagenumbers $10 \times$ \bye'
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
 restricted \write18 enabled.
**entering extended mode
[1{/home/wchargin/.texmf-var/fonts/map/pdftex/updmap/pdftex.map}]</usr/share/te
xlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb></usr/share/texlive/t
exmf-dist/fonts/type1/public/amsfonts/cm/cmsy10.pfb>
Output written on texput.pdf (1 page, 15577 bytes).
Transcript written on texput.log.
$ convert -density 300 -trim texput.pdf times.png
$ open times.png 
```
> ![Same output by pdftex](https://cloud.githubusercontent.com/assets/4317806/9838388/54bef4fa-5a11-11e5-862e-e25ff66e0b6f.png)

Consult the following table from Chapter 18 of the TeXbook for the atom conversion rules:
![Table of atom conversions](https://cloud.githubusercontent.com/assets/4317806/9838389/60158a94-5a11-11e5-96b6-9fdc2b1de8d9.png)

**Comment by spicyj** [comment] 2015-09-13 19:19
I'm going to call this a dupe of #4. As you might know, you can work around this by doing `10{\times}`.

**Closed by spicyj** 2015-09-13 19:19 UTC

**Comment by WChargin** [comment] 2015-09-13 21:36
(Workaround is to write `10{\times}`.)

**Comment by WChargin** [comment] 2015-09-13 21:37
Yep! That was my workaround. Thanks!
