### ISSUE TITLE
Feature request: HTML inside mathematics

### ISSUE THREAD

**Issue by jabacchetta** [Khan/KaTeX#1774] opened 2018-11-02 16:08 UTC
[jqMath](https://mathscribe.com/author/jqmath.html) allows for things like text inputs as part of a fraction (where a user can fill in the inputs). An example of this can be seen on the site (search for `\html`).

As far as I know, this isn't possible with KaTeX, but would love to see the feature added.

**Comment by edemaine** [comment] 2018-11-02 17:17
I believe this is the same request as #1596. Also related to #1771 if you'd care to comment.

**Comment by ylemkimon** [comment] 2018-11-05 15:39
Duplicate of #1596

**Closed by ylemkimon** 2018-11-05 15:39 UTC
