### ISSUE TITLE
An ParseError is thrown when entering Chinese characters

### ISSUE THREAD

**Issue by gujunhk** [Khan/KaTeX#483] opened 2016-05-27 11:12 UTC
In the [Demo Page](https://khan.github.io/KaTeX/)
when I enter
````latex
\color{red}{ABC}
```
everything goes ok.

However, 
```latex
\color{red}{ABC中文}
```
throws an exception
```
katex.min.js:1 Uncaught ParseError: KaTeX parse error: Expected '}', got '中' at position 30: color{red}{ABC中̲文}}
```
Perhaps KaTeX *does not* support ``CJK`` or ``Unicode`` chars?

**Comment by kevinbarabash** [comment] 2016-05-27 15:45
Duplicate of https://github.com/Khan/KaTeX/issues/380.  KaTeX currently doesn't support CJK or Unicode, but we're slowly working on it.

**Closed by kevinbarabash** 2016-05-27 15:45 UTC
