### ISSUE TITLE
A problem about subscript and superscript in QtWebKit4 

### ISSUE THREAD

**Issue by iwtwiioi** [Khan/KaTeX#906] opened 2017-09-27 08:56 UTC
I downloaded the latest KaTeX and use it in a web browser developed by me.
But I found there is a problem about subscript and superscript like the following picture:
![qq 20170927164913](https://user-images.githubusercontent.com/9914848/30904214-e920d252-a3a3-11e7-8a5c-63b35be4d071.jpg)
```
$$
\begin{aligned}
a_i \\
b_j^2 \\
c^2
\end{aligned}
$$
```
Looks very bad, isn't it?
Can someone tell me how to fix that problem by modifying KaTeX sources?Thx>_<
Sorry for my bad English.

**Comment by edemaine** [comment] 2017-09-27 12:10
I suspect this is either quirks mode or a failure to load the CSS file (and thus the fonts). Can you confirm that you're loading `katex.min.css`, and that you're using `<!DOCTYPE html>`?

**Comment by iwtwiioi** [comment] 2017-09-27 13:47
@edemaine 
yeah, I'm pretty sure I have loaded `katex.min.css` and used `<!DOCTYPE html>`.

**Comment by edemaine** [comment] 2017-09-27 13:50
@iwtwiioi We'll need more information to help you here. The example renders fine in the [demo page](https://khan.github.io/KaTeX/).

**Comment by iwtwiioi** [comment] 2017-09-27 14:01
@edemaine 
On Windows 10, the problem exists:
Environment:
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32
PySide 1.2.4, installed by command `pip install pyside --only-binary :all:`
KaTex, the latest version, released on 08 Aug

Here is another example:
![qq 20170927215958](https://user-images.githubusercontent.com/9914848/30917747-49ec6a4e-a3cf-11e7-9a97-17884a071dcd.jpg)
made by `$$ans=|S|-|A_i|+\sum_{i < j} |A_i \cap A_j|-...+ |A_1 \cap A_2 \cap A_3 \cap A_4|$$`

On Linux, every thing is ok.

My project home:![ITree](https://github.com/iwtwiioi/ITree)

**Comment by edemaine** [comment] 2017-09-27 14:49
I guess I'm confused why you think this is a bug with KaTeX, instead of a bug with your custom web browser, given that these examples render fine in Chrome, and not in your web browser...

**Comment by kevinbarabash** [comment] 2017-09-27 15:01
Looks like a duplicate of #45.  The problem seems to be with vlists that use shifts.  The `\sum_{i < j}` layout doesn't use `shift` in the vlist while all of the subscripts do.

**Comment by iwtwiioi** [comment] 2017-09-27 15:28
@edemaine 
I didn't say this is a bug with KaTeX, I just want to ask for a way to modify the KaTeX's sources to satisfy my browser...QAQ

**Comment by PeterBocan** [comment] 2017-09-30 12:54
I would suggest you to upgrade to Qt 5, because WebKit in Qt 4 is rather quite outdated.

**Comment by edemaine** [comment] 2017-12-12 20:32
Closing this barring further information. Let us know the result of upgrading to Qt 5.

**Closed by edemaine** 2017-12-12 20:32 UTC
Labels: more info needed
