### ISSUE TITLE
Is it possible to display \LaTeX as in proper LaTeX?

### ISSUE THREAD

**Issue by oblitum** [Khan/KaTeX#463] opened 2016-04-26 22:23 UTC
I'd like to have `\LaTeX` printed as in LaTeX/MathJax, is it possible?

**Comment by xymostech** [comment] 2016-04-26 22:25
KaTeX doesn't currently support the `\LaTeX` symbol, if that's what you're asking. This is a duplicate of #224

**Closed by xymostech** 2016-04-26 22:25 UTC

**Comment by oblitum** [comment] 2016-04-26 22:27
@xymostech ok, thanks!
