### ISSUE TITLE
How to show vector?

### ISSUE THREAD

**Issue by rslbtdk** [Khan/KaTeX#466] opened 2016-05-01 10:46 UTC
Just like the picture below：

![vector](https://cloud.githubusercontent.com/assets/17931024/14941405/853c6d80-0fcc-11e6-8f91-05f1d27a03a0.JPG)

I found there is no \overrightarrow,so how to do it?

**Comment by kevinbarabash** [comment] 2016-05-01 16:21
Closing as duplicate of https://github.com/Khan/KaTeX/issues/402.

**Closed by kevinbarabash** 2016-05-01 16:21 UTC
