### ISSUE TITLE
Overlapping symbols in some math expressions

### ISSUE THREAD

**Issue by erusev** [Khan/KaTeX#429] opened 2016-01-24 20:23 UTC
```
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix} 
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0 \\
\end{vmatrix}
```
outputs:
![image](https://cloud.githubusercontent.com/assets/184170/12538701/219565b4-c2e9-11e5-9a2b-dcb68366890d.png)

**Comment by kevinbarabash** [comment] 2016-01-24 23:57
The KaTeX rendering matches the LaTeX rendering for this example.  You can adjust the spacing between rows in the following way:
```
\begin{vmatrix} 
i & j & k \\[0.5em]
\frac{\partial X}{\partial u} &
\frac{\partial Y}{\partial u} & 0 \\[1em]
\frac{\partial X}{\partial v} &
\frac{\partial Y}{\partial v} & 0 
\end{vmatrix}
```
Which gives the following rendering:
![screen shot 2016-01-24 at 3 55 50 pm](https://cloud.githubusercontent.com/assets/1044413/12539960/00bcf4a0-c2b3-11e5-97c2-feb8f75ba03c.png)

The delimiters should be a little taller.

**Comment by xymostech** [comment] 2016-01-25 01:41
Duplicate of #331

**Closed by xymostech** 2016-01-25 01:41 UTC

**Comment by erusev** [comment] 2016-01-25 07:28
@kevinbarabash Thanks.
