### ISSUE TITLE
log_\sqrt{3}9 should work, but doesn't

### ISSUE THREAD

**Issue by qbolec** [Khan/KaTeX#247] opened 2015-06-13 10:24 UTC
I'm trying to migrate from MathJax, but several things still do not work:

Uncaught ParseError: KaTeX parse error: Got function '\sqrt' with no arguments as subscript at position 6: a=log_̲\sqrt{3}9

Uncaught ParseError: KaTeX parse error: Optional arguments to \sqrt aren't supported yet at position 7: \sqrt[4̲]{9}\cdot\sqrt

Is there any way around these bugs?

**Comment by kevinb7** [comment] 2015-06-13 16:37
@qbolec The first one definitely looks like a bug.  The second one however is a duplicate of https://github.com/Khan/KaTeX/issues/48.  If you build from source it should work.

**Comment by kevinb7** [comment] 2015-06-13 16:40
Interestingly ```a = log_\frac{1}{2}9``` works fine.

**Comment by spicyj** [comment] 2015-06-15 21:30
Hopefully as simple as adjusting the greediness values:

https://github.com/Khan/KaTeX/blob/9869d59cadb009fdd8b07f8516ff62a5a8f76b3a/src/functions.js

**Comment by kevinb7** [comment] 2015-06-15 23:45
LaTeX also throws an error on ```\log_\sqrt{3}9```.  In this case I would say MathJax's behavior is incorrect.  Since we'd like to match LaTeX behavior whenever possible I'm going close this as "won't fix".  

@qbolec Sorry, you'll have to add some extra braces around the ```\sqrt```.

**Closed by kevinb7** 2015-06-15 23:46 UTC
