### ISSUE TITLE
support for STIX web fonts, other 

### ISSUE THREAD

**Issue by jpsteinb** [Khan/KaTeX#1450] opened 2018-06-25 21:19 UTC
I'm sorry to reopen/neg about what is seemingly an old issue, but is there any plan to supper STIX web fonts soon?

I want to use KaTeX in my project, but the lack of STIX fonts is holding me back.

If somebody is already working on this, would be glad to help.

**Comment by kevinbarabash** [comment] 2018-06-26 02:22
No plans to do this right away, but we would like to do this eventually.  @HosseinAgha has done some work in this area, please see #1269.  I'm closing this as a duplicate of #123.

**Closed by kevinbarabash** 2018-06-26 02:22 UTC
