### ISSUE TITLE
poor spacing in fractions

### ISSUE THREAD

**Issue by jason-s** [Khan/KaTeX#542] opened 2016-10-06 19:37 UTC
`$\alpha _ e = \frac{3K _ e I _ \text{max}}{2 J}$`

KaTeX: 

![image](https://cloud.githubusercontent.com/assets/738893/19167677/a01a7810-8bc1-11e6-8f10-0b56356219cc.png)

MathJax:

![image](https://cloud.githubusercontent.com/assets/738893/19167685/acc12a0a-8bc1-11e6-93df-a72f198a1e3e.png)

**Comment by sthoch** [comment] 2016-10-07 08:25
Could be a font-size related issue like #41. At 4-5pt I get a similiar rendering to yours, above that, sometime the subscript touch the fraction bar. How small are you rendering? In what context are you using KaTeX?

**Comment by gagern** [comment] 2016-10-07 09:14
Yes, this looks very much like #41. Again the vertical spacing appears correct at larger sizes, with “correct” meaning “as TeX does it”:

![Comparison](https://cloud.githubusercontent.com/assets/190759/19184781/fa6ffa84-8c7e-11e6-831c-23f758b2ffce.png)

TeX in green, KaTeX in red. You see that the vertical spacing matches even though the horizontal one does not.

I'm closing this as a duplicate of #41.

**Closed by gagern** 2016-10-07 09:14 UTC
Labels: duplicate
