### ISSUE TITLE
\mathbf with subscripts/superscripts causes incorrect spacing

### ISSUE THREAD

**Issue by jason-s** [Khan/KaTeX#534] opened 2016-09-17 14:48 UTC
```
\[ A*B+C-D = E \]
\[ A_1 * B^2 + C_3^4 + D^5_6 = E_0 \]
\[ \mathbf{A}*\mathbf{B}+\mathbf{C}-\mathbf{D} = \mathbf{E} \]
\[ \mathbf{A}_1 * \mathbf{B}^2 + \mathbf{C}_3^4 + \mathbf{D}^5_6 = \mathbf{E}_0 \]
```

KaTeX on Chrome 52.0.2743.116 m:

![image](https://cloud.githubusercontent.com/assets/738893/18608949/2990f28e-7cab-11e6-80e6-d561c1b442a1.png)

MathJax on Chrome 52.0.2743.116 m:

![image](https://cloud.githubusercontent.com/assets/738893/18608948/1139f032-7cab-11e6-9a0c-8551f15f32d5.png)

**Comment by kevinbarabash** [comment] 2016-09-17 19:57
@jason-s thanks for the bug report.  I feel like this and https://github.com/Khan/KaTeX/issues/533 probably have the same root cause.

**Comment by kevinbarabash** [comment] 2016-12-08 00:53
Fixed on `master`.

**Closed by kevinbarabash** 2016-12-08 00:53 UTC
Labels: bug, help wanted

**Comment by jason-s** [comment] 2016-12-08 18:00
excellent... is there a release plan or roadmap for upcoming releases of KaTeX? (just wondering when this propagates to the default version available on the webpage https://khan.github.io/KaTeX/ )

**Comment by jason-s** [comment] 2016-12-08 18:02
I rewrote test case for one equation (so it can be easily tested on the KaTeX page https://khan.github.io/KaTeX/)

```
\begin{aligned}
A*B+C-D = E \cr
A_1 * B^2 + C_3^4 + D^5_6 = E_0 \cr
\mathbf{A}*\mathbf{B}+\mathbf{C}-\mathbf{D} = \mathbf{E} \cr
\mathbf{A}_1 * \mathbf{B}^2 + \mathbf{C}_3^4 + \mathbf{D}^5_6 = \mathbf{E}_0
\end{aligned}
```

**Comment by kevinbarabash** [comment] 2016-12-08 20:27
@jason-s upcoming release either before end-of-year, or early in the new year.  Updating the site is a separate step.
