### ISSUE TITLE
Lorenz equations don't seem to work

### ISSUE THREAD

**Issue by jackparmer** [Khan/KaTeX#412] opened 2015-12-13 02:54 UTC
Via http://www.intmath.com/cg5/katex-mathjax-comparison.php?processor=MathJax

![image](https://cloud.githubusercontent.com/assets/1865834/11765183/92e94b9a-a11a-11e5-9be4-d109a518187c.png)

Seems related to: https://github.com/Khan/KaTeX/issues/61

**Comment by kevinbarabash** [comment] 2015-12-23 01:20
```
\begin{aligned}
\dot{x} & = \sigma(y-x) \\ 
\dot{y} & = \rho x - y -xz \\ 
\dot{z} & = -\beta z + xy
\end{aligned}
```
produces the following in KaTeX (not yet deployed):
<img width="624" alt="screen shot 2015-12-22 at 5 16 29 pm" src="https://cloud.githubusercontent.com/assets/1044413/11969558/e0a96bfa-a8cf-11e5-87b6-fc58f44f17e6.png">

I'm going to close this a duplicate of https://github.com/Khan/KaTeX/issues/61.

**Closed by kevinbarabash** 2015-12-23 01:20 UTC
