### ISSUE TITLE
Superscript in the denominator of a fraction partially covered by line

### ISSUE THREAD

**Issue by MKevin3** [Khan/KaTeX#408] opened 2015-12-02 13:13 UTC
![ios katex](https://cloud.githubusercontent.com/assets/2380650/11531637/e973c4cc-98c3-11e5-8f79-c4c2a479c0a0.png)

This occurs on both iOS and Android. Here is what it looks like in MathJax for comparison

![mathjax](https://cloud.githubusercontent.com/assets/2380650/11531650/fb549914-98c3-11e5-8bd1-8eac1d5b6a45.png)

It is not a deal breaker but it would be nice to have more vertical spacing between the line and the denominator.

**Comment by kevinbarabash** [comment] 2015-12-02 15:23
What font size are you using?  Is this with `\displaystyle`?

**Comment by MKevin3** [comment] 2015-12-02 15:46
We get the data from the server - I hope this is a pared down version that shows the issue for you

display style is inline

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css">
<script src="http://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js"></script>
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function(event) {
    var imgs=document.querySelectorAll('img[src*="formula_image"]');
    for(var i=0;i<imgs.length;i++){
      var img = imgs[i];
      var formula = img.getAttribute("title");
      if(!formula || (formula && formula.trim() == "")) {
        formula=img.getAttribute("alt");
      }
      if(formula && formula.trim() != "") {
        try {
          var span=document.createElement("span");
          katex.render(formula,span);
          span.setAttribute("class","formula_image");
          img.parentNode.insertBefore(span,img.nextSibling);
          span.style.display="block";
          imgs[i].style.display="none";
        }
        catch(err) {}
      }
    }
  });
</script>
</head>
<body>
<div class="main">
​
​
<div class="box question">
<p>
<img title="\frac{2x^2-5x-12}{x^2-11x+28}" src="http://vt-s3-files.s3.amazonaws.com/uploads/formula_image/image/252552/gif.latex" alt="" style="display: none;">
</p>
</div>
</div>
​
</body></html>

**Comment by sschendel** [comment] 2015-12-02 16:20
We are not using \displaystyle in this case.  We have javascript that pulls formula from img title attributes and replaces image with rendered content or falls back to image.  Attached is example of issue.  Tried render with displayMode=true.  That helps, but we'd like to keep the content inline, if possible.  We cannot change content, unfortunately.  

https://gist.github.com/sschendel/f393c3ae70e722639d44

**Comment by kevinbarabash** [comment] 2015-12-23 01:31
Here's the LaTeX rendering for reference:
<img width="54" alt="screen shot 2015-12-22 at 5 30 04 pm" src="https://cloud.githubusercontent.com/assets/1044413/11969663/ab5fe79c-a8d1-11e5-8d01-ca52fd8d83f6.png">

With KaTeX we're aiming to match LaTeX's rendering.

**Comment by gagern** [comment] 2016-10-07 10:11
This sounds related to #41. It might even shed some new light on that one. Here is a comparison of TeX (green) and KaTeX (red) rendering:

![Comparison](https://cloud.githubusercontent.com/assets/190759/19185173/c7f72a1c-8c80-11e6-852d-38c1ce7ed59e.png)

What I consider really interesting here is the fact that TeX renders the exponent in the numerator in a higher position than KaTeX, but the one in the denominator in a lower position. Things get even more interesting if we take that image and move both parts of the fraction to a common baseline and zoom in a bit:

![At common baseline](https://cloud.githubusercontent.com/assets/190759/19185573/84e2cfc2-8c82-11e6-91d6-2a89c557ae77.png)

So the differently shifted exponents are already present in both versions. It's just that the difference is more pronounced in TeX than it is in KaTeX. So perhaps we need to identify where that is happening, and see we match the amount of shift used by TeX.

I guess the cause for these shifts is the fact that [denominators use cramped style](https://github.com/Khan/KaTeX/blob/v0.6.0/src/Style.js#L115-L116), which [leads to different shifts](https://github.com/Khan/KaTeX/blob/v0.6.0/src/buildHTML.js#L303-L307). So perhaps our [σ<sub>14</sub> and σ<sub>15</sub>](https://github.com/Khan/KaTeX/blob/v0.6.0/src/fontMetrics.js#L33-L34) are wrong? [This comment](https://github.com/Khan/KaTeX/blob/v0.6.0/src/fontMetrics.js#L12-L19) describes where they came from:

> These font metrics are extracted from TeX by using
>
> ```tex
> \font\a=cmmi10
> \showthe\fontdimenX\a
> ```
> where `X` is the corresponding variable number. These correspond to the font
> parameters of the symbol fonts. In TeX, there are actually three sets of
> dimensions, one for each of textstyle, scriptstyle, and scriptscriptstyle,
> but we only use the textstyle ones, and scale certain dimensions accordingly.
> See [the TeXbook](http://www.ctex.org/documents/shredder/src/texbook.pdf), page 441.

But this doesn't work for me:

```
$ tex -interaction=nonstopmode '\font\a=cmmi10\showthe\fontdimen14\a'
This is TeX, Version 3.14159265 (TeX Live 2016) (preloaded format=tex)
! Font \a has only 7 fontdimen parameters.
```

Following the manual I get these instead:

```
$ tex -interaction=nonstopmode '\showthe\fontdimen14\textfont2' '\showthe\fontdimen15\textfont2' '\showthe\fontdimen14\scriptfont2' '\showthe\fontdimen15\scriptfont2'
> 3.62892pt.
<*> \showthe\fontdimen14\textfont2 ...
> 2.88889pt.
<*> ... \showthe\fontdimen15\textfont2 ... 
> 3.01779pt.
<*> ... \showthe\fontdimen14\scriptfont2 ...
> 1.99998pt.
<*> ... \showthe\fontdimen15\scriptfont2
```

OK, what do we see here? For scriptstyle [we scale fonts by 0.7](https://github.com/Khan/KaTeX/blob/v0.6.0/static/katex.less#L212) compared to text style. So assuming a 10pt font we are essentially using σ<sub>14</sub> = 0.7⋅3.63 = 2.541 < 2.889 and σ<sub>15</sub> = 0.7⋅2.89 = 2.023 > 2.000. So yes, placement of these exponents is wrong, and we should find a way to fix this. I guess we will need to store all the different values of σ for the different styles, so that we can pick the one appropriate to the current style.

**Comment by gagern** [comment] 2016-10-07 10:28
I have to concede that the observed difference between KaTeX and TeX placement of exponents in the denominator appears to differ by more than 0.02pt, so I don't know what else could cause this discrepancy. I thought it might be a different placement of the baseline in the TeX script fonts, but I can see no significant difference there (comparing `08{\scriptstyle 08}{\scriptscriptstyle 08}`):

![Baseline comparison](https://cloud.githubusercontent.com/assets/190759/19187010/5c2cfd08-8c89-11e6-8356-22f69cb58919.png)

**Comment by xymostech** [comment] 2016-10-07 16:40
> OK, what do we see here? For scriptstyle we scale fonts by 0.7 compared to text style. So assuming a 10pt font we are essentially using σ14 = 0.7⋅3.63 = 2.541 < 2.889 and σ15 = 0.7⋅2.89 = 2.023 > 2.000. So yes, placement of these exponents is wrong, and we should find a way to fix this. I guess we will need to store all the different values of σ for the different styles, so that we can pick the one appropriate to the current style.

Oh! That's a really cool calculation to look at, interesting that σ14 is off by so much! I remember a discussion before about adding style-specific metrics for a bunch of the other metrics that change like this, we already did that for one of the metrics: https://github.com/Khan/KaTeX/blob/v0.6.0/src/fontMetrics.js#L103 We could try doing something similar for σ14 and see if that fixes some of the discrepancies?

**Comment by kevinbarabash** [comment] 2016-10-08 02:07
I have a hunch that TeX is adjust the baseline of superscripts (and subscripts) based on what's above/below and its distance from the superscript/subscript.  Now I just need find proof in the TeXbook.

**Comment by kevinbarabash** [comment] 2016-10-08 02:52
[Where are the math font parameters](http://tex.stackexchange.com/questions/318483/where-are-the-math-font-parameters) helped me to figure out what the sigma values are for `\scriptfont2` and `\scriptscriptfont2`.  Once you know which font files are mapped to these internal font indicators you can run `tftopl` which will return font dimensions as well as TeX font metrics (width, height, depth).

Here's the TeX code I used:
```
\documentclass{article}
\usepackage{amsmath}

\begin{document}

$a$ \expandafter\show\the\textfont2 \expandafter\show\the\scriptfont2 \expandafter\show\the\scriptscriptfont2

\stop
```

After running that an hitting enter a couple of times I got:
```
> \OMS/cmsy/m/n/10=select font cmsy10.
<inserted text> \OMS/cmsy/m/n/10 
                                 
l.6 $a$ \expandafter\show\the\textfont2 
                                        \expandafter\show\the\scriptfont2 \e...

? 
> \OMS/cmsy/m/n/7=select font cmsy7.
<inserted text> \OMS/cmsy/m/n/7 
                                
l.6 ...extfont2 \expandafter\show\the\scriptfont2 
                                                  \expandafter\show\the\scri...

? 
> \OMS/cmsy/m/n/5=select font cmsy5.
<inserted text> \OMS/cmsy/m/n/5 
                                
l.6 ...nt2 \expandafter\show\the\scriptscriptfont2
                                                  
? 
```

This let me know that:
```
\textfont2 = cmsy10
\scriptfont2 = cmsy7
\scriptscriptfont2 = cmsy5
```

Then I ran `tftopl cmsy10`, `tftopl cmsy7` and `tftop cmsy5`.  Here's the `FONTDIMEN` section from `cmsy10`:
```
   (SLANT R 0.25)
   (SPACE R 0.0)
   (STRETCH R 0.0)
   (SHRINK R 0.0)
   (XHEIGHT R 0.430555)
   (QUAD R 1.000003)
   (EXTRASPACE R 0.0)
   (NUM1 R 0.676508)
   (NUM2 R 0.393732)
   (NUM3 R 0.443731)
   (DENOM1 R 0.685951)
   (DENOM2 R 0.344841)
   (SUP1 R 0.412892)
   (SUP2 R 0.362892)  // sigma 14
   (SUP3 R 0.288889)  // sigma 15
   (SUB1 R 0.15)
   (SUB2 R 0.247217)
   (SUPDROP R 0.386108)
   (SUBDROP R 0.05)
   (DELIM1 R 2.389999)
   (DELIM2 R 1.01)
   (AXISHEIGHT R 0.25)
```

Here are the sigma values for all three fonts together:
```
\textfont2 (cmsy10):
sigma_14 = 0.362892
sigma_15 = 0.288889

\scriptfont2 (cmsy7):
sigma_14 = 0.431115
sigma_15 = 0.285714

\scriptscriptfont2 (cmsy5):
sigma_14 = 0.403555
sigma_15 = 0.294446
```

We should definitely do the TODO on https://github.com/Khan/KaTeX/blob/v0.6.0/src/fontMetrics.js#L103.  Hopefully it will fix a bunch other discrepancies.

**Comment by gagern** [comment] 2016-10-08 08:40
> an hitting enter a couple of times

`-interaction=nonstopmode` helps there.

> you can run `tftopl` which will return font dimensions

If I read the output correctly, `tftopl` will report these dimensions in em, while TeX reports them in pt. Just for comparison, here is a way to read them all from LaTeX:

```sh
latex -jobname=sizes -interaction=nonstopmode \
'\documentclass{article}\usepackage{amsmath}\begin{document}$'\
$(for i in text script scriptscript
  do echo '\showthe\'$i'font2'
     for ((j=1;j<=22;++j))
     do echo '\showthe\fontdimen'$j\\$i'font2'
     done
  done
)' $\end{document}'
```

Does display style re-use the values from the text font? I guess so.

> We should definitely do the TODO on https://github.com/Khan/KaTeX/blob/v0.6.0/src/fontMetrics.js#L103.

:+1: to that.

**Comment by kevinbarabash** [comment] 2017-09-15 04:02
A number of changes have been made recently to how we handle vertical space.  Also, the TODO reference above has been done.  Here's KaTeX's current rendering:

<img width="52" alt="screen shot 2017-09-14 at 11 58 49 pm" src="https://user-images.githubusercontent.com/1044413/30466021-dad5c342-99a8-11e7-83bf-6e5c59dabcf9.png">

I'm going to close this for now.  @MKevin3 if you update to the latest version and you still see this on Android or iOS please re-open.

**Closed by kevinbarabash** 2017-09-15 04:02 UTC
Labels: bug
