### ISSUE TITLE
KaTex rendering  problem on mobile page.[overlapping problem]

### ISSUE THREAD

**Issue by prasanthown** [Khan/KaTeX#543] opened 2016-10-08 10:16 UTC
![image](https://cloud.githubusercontent.com/assets/20787744/19212400/06af992c-8d6e-11e6-8d52-f0f22b295eae.png)
 Why they are show like this and how to solve it.I was rendering the Katex into `li` tag
Here is My code:
        `$('.step_box').append("<li>"+katex.renderToString('x_2\=\\frac{-(10x^2)-5x}{10x^3}')+"</li>");`

**Comment by kevinbarabash** [comment] 2016-10-08 14:20
I'm surprised this is even rendering.  I tried rendering `x_2\=\\frac{-(10x^2)-5x}{10x^3}` on khan.github.io/KaTeX and got a ParseError.  After removing unnecessary backslashes it rendered `x_2=\frac{-(10x^2)-5x}{10x^3}` correctly.

![screen shot 2016-10-08 at 10 18 47 am](https://cloud.githubusercontent.com/assets/1044413/19213692/a485e544-8d40-11e6-861a-07527e734c1b.png)

@prasanthown can you try it again without the extra backslashes?  Also, what version are you using?

**Comment by gagern** [comment] 2016-10-08 17:00
Is this a page we can visit? If not, can you create a static version which reproduces the problem? From what browser (name and version) was the screenshot taken? Can this be reproduced with other browsers?

**Comment by xymostech** [comment] 2016-10-08 21:11
@prasanthown Do you have a doctype on your page? KaTeX doesn't work in quirks mode, so you need to have a doctype on your page. Check if you have something like `<!DOCTYPE html>` at the top of your page.

@kevinbarabash it's in a javascript string, so the backslashes are escaping, so it makes sense that it rendered.

**Comment by kevinbarabash** [comment] 2016-10-08 21:53
@xymostech I think I need more sleep.  I typed `"x_2\=\\frac{-(10x^2)-5x}{10x^3}"` into the console and got back `"x_2=\frac{-(10x^2)-5x}{10x^3}"` so it looks like browser is ignores the `\` in front of the `=`.

**Comment by kevinbarabash** [comment] 2016-10-08 21:57
I'm really curious to find out where `67.08203932499369` is coming from.

**Comment by kevinbarabash** [comment] 2017-07-31 03:15
I'm going to close this as it was probably a doctoring issue and support for quirks mode has just landed on `master`.

**Closed by kevinbarabash** 2017-07-31 03:15 UTC

**Comment by kevinbarabash** [comment] 2017-07-31 03:27
I ended up reverting https://github.com/Khan/KaTeX/pull/608 b/c quirks mode looks bad.  I'm going to keep this issue closed though due to lack of additional information.
