### ISSUE TITLE
 KaTeX's array environment doesn't support  *

### ISSUE THREAD

**Issue by nikilarigela** [Khan/KaTeX#1726] opened 2018-09-24 14:35 UTC
in mathjax it renders , but in katex it shows (``  KaTeX parse error: Unknown column alignment: * at position 50: …{\begin{array}{*̲{20}{c}} {\frac… ``)

`` f\left( x \right)\, = \,\,\left\{ {\begin{array}{*{20}{c}}
  {\frac{{ - \sin \,\left\{ {\cos \,x} \right\}}}{{x - \pi /2}}}&{x\, \ne \,\frac{\pi }{2}} \\ 
  2&{x\, = \,\frac{\pi }{2}} 
\end{array}\,,} \right ``

![](https://user-images.githubusercontent.com/9781249/45947562-569eeb80-c012-11e8-8ee2-304d95b33142.png)

**Comment by edemaine** [comment] 2018-09-24 15:49
This is a duplicate of issue #269. For now, you can use `\begin{array}{cc}`.

**Closed by edemaine** 2018-09-24 15:49 UTC

**Comment by nikilarigela** [comment] 2018-09-26 09:40
\begin{array}{cc}. it didn't work. I want to know if below syntax i wanted to generate what is the Tex will be.

![](https://user-images.githubusercontent.com/9781249/45947562-569eeb80-c012-11e8-8ee2-304d95b33142.png)

**Comment by nikilarigela** [comment] 2018-09-26 17:05
Thanks @edemaine,
I forgot to put period at end.(i think i'm in phantasm).

**Comment by kevinbarabash** [comment] 2018-10-13 01:32
What does the period do?

**Comment by edemaine** [comment] 2018-10-13 01:46
`\right` needs an argument. `\right.` matches a `\left' but without drawing anything.
