### ISSUE TITLE
array environment has less vertical spacing than mathjax

### ISSUE THREAD

**Issue by kasperpeulen** [Khan/KaTeX#594] opened 2016-12-29 13:37 UTC
![image](https://cloud.githubusercontent.com/assets/1035299/21545008/4a1bc20c-cdd4-11e6-981d-8fb008593968.png)

left is mathjax right is katex, it is subtle, but I find the mathjax equation look a bit better, the extra vertical spacing makes it look less noisy

**Comment by kevinbarabash** [comment] 2017-01-01 01:48
@kasperpeulen can you provide the TeX source?

**Comment by PeterBocan** [comment] 2017-01-01 10:23
Duplicate of #531 ?

**Comment by gagern** [comment] 2017-01-01 18:08
The cause of #531 is an `\openup` call which I found in the TeX sources of `alined`, but haven't reproduced on the KaTeX side yet. If one can find such an `\openup` call for `array` environments, then it would indeed be a duplicate. But I'd like to see that identified first, to make sure we are handling this correctly, not merely guessing.

I'd also like to see a texdiff for this, check that we are indeed doing things different from LaTeX, because in cases where LaTeX and MathJax differ we tend to emulate the former not the latter. So I second Kevin's request for TeX sources. I *guess* it might be a `{rcl}` aligned three-column array.

**Comment by kasperpeulen** [comment] 2017-01-03 13:14
@kevinbarabash 
Here is the source:

```latex
    \begin{array}{rclcl} 
    2x + 5 &=& 4x -3 &&\\
    2x + 5 - 4x &=& 4x -3 - 4x &&\\
    -2x +5 &=& -3 &&\\
    -2x +5 -5&=& -3 -5&&\\
    -2x  &=& -8&&\\
     x  &=& 4&&
     \end{array} 
```

**Comment by gagern** [comment] 2017-01-03 15:14
I've adjusted this test case slightly to fit it into the 1024px width of our screenshot tests. The result indicates that our current behavior matches what LaTeX does:

![Comparison with LaTeX](https://cloud.githubusercontent.com/assets/190759/21611912/351d70d6-d1cf-11e6-8e95-cf77e2bb4aa7.png)

KaTeX output in red, mostly due to thicker font. LaTeX output in green, indicating a slight difference in vertical placement of the = in relation to the rest. But most things are white or black, indicating that KaTeX and LaTeX agree. In particular there is no noticable drift where things would look more colored at some vertical positions but less at others. So I'd say KaTeX is doing things the LaTeX way. If MathJax decides to space things differently, that is their decision, but the reference for KaTeX is LaTeX, not MathJax.

**Comment by kevinbarabash** [comment] 2017-01-05 14:27
@kasperpeulen in the future it might be nice to add `\addtolength`, but for now you can use `\\[1em]` to adjust the space between lines.

**Closed by kevinbarabash** 2017-01-05 14:27 UTC
