### ISSUE TITLE
About dist folder

### ISSUE THREAD

**Issue by pvnr0082t** [Khan/KaTeX#641] opened 2017-01-21 04:44 UTC
Hi @xymostech, @gagern ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs).
I found that there is no `dist` folder at the latest release. I'd like to discuss if it's possible to put the `dist` folder back to GitHub repo because the auto-updater in cdnjs will update the library from GitHub repo automatically follow the auto-update config instead of manually download files by ourselves. Thanks!

https://github.com/cdnjs/cdnjs/issues/10337

**Comment by gagern** [comment] 2017-01-21 10:15
Essentially a duplicate of #613. We need to release 0.7.1 and have that `dist` folder, I think.

**Comment by kevinbarabash** [comment] 2017-01-22 19:32
https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js is now available.  It looks like they're in the process of update the KaTeX entry as 0.6.0 is still the most recent version in the dropdown on https://cdnjs.com/libraries/KaTeX.

**Comment by gagern** [comment] 2017-01-22 21:41
Let's keep this open till the dropdown catches up, shall we?

**Comment by kevinbarabash** [comment] 2017-09-15 12:36
The cdnjs dropdown is up to date.

**Closed by kevinbarabash** 2017-09-15 12:36 UTC
