### ISSUE TITLE
Possible to write KaTeX w/different languages?

### ISSUE THREAD

**Issue by IndieKA** [Khan/KaTeX#383] opened 2015-11-06 17:10 UTC
Is it possible to write KaTeX w/different languages like French, Spanish, or Japanese?
I know this isn't a issue, but I was only wondering. Please don't close this, I would love to have an answer.

**Comment by kevinbarabash** [comment] 2015-11-06 23:38
Not currently.  Please see https://github.com/Khan/KaTeX/issues/380 for a more in depth of explanation of why.  I'm closing this as a duplicate of that issue.

**Closed by kevinbarabash** 2015-11-06 23:38 UTC
