### ISSUE TITLE
"KaTeX parse error: Expected 'EOF', got '<bla>' at position 1" when input pure Chinese character(s)

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Khan/KaTeX#895] opened 2017-09-19 19:28 UTC
![_257](https://user-images.githubusercontent.com/13408130/30611159-2a01f13a-9db3-11e7-8e41-2483e80bd39e.png)

control case: 

![_258](https://user-images.githubusercontent.com/13408130/30612763-36a304a6-9db8-11e7-8d14-9faf9a4f7b31.png)

## Bug Reproducing Instructions
1. Browse [KaTeX – The fastest math typesetting library for the web](https://khan.github.io/KaTeX/)
1. Input any C(JK) characters, this attempt uses "測試"

## Expected Behavior
"測試" printed in "See how it renders with KaTeX: " field, presumably to be in italic just as any regular text

## Current Behavior
The "See how it renders with KaTeX: " field spews out the following error: 

```
KaTeX parse error: Expected 'EOF', got '測' at position 1: 測̲試
```

**Comment by kevinbarabash** [comment] 2017-09-19 19:46
@Lin-Buo-Ren awesome bug report.  You can use CJK characters within `\text`.  I'm curious about the use cases of natural language strings outside of `\text`?

**Comment by Lin-Buo-Ren** [comment] 2017-09-19 19:58
@kevinbarabash 

> I'm curious about the use cases of natural language strings outside of \text?

I'm not sure as I'm not really acquainted with LaTeX and simply using it to write math equations in Markdown documents on GitBook, never used `\text` before ;)

**Comment by 07pepa** [comment] 2017-11-23 09:07
I know it is utf8 characters related... looked into sources of katex on font and there are only printable english chars maybe it is related to multy-byte-ness of non ascii chars
 
PS. czech chars  like "ěščřžýáíéťňůú" and theri capitalizated version"ĚŠČŘŽÝÁÍÉŤŇŮÚ" do not work also and  utf-8 emoji also not work 😭.....only sotlution  is ( if input box is utf-8) do utf 8 filter if it thinking it is procesing ascii)

it can look like this ( is not corect im writing in hurry) //will return nuber of bytes that )
`function utf8(char input)
var locarvar=0;
{
if (input>128){
shr input; // shift right input
for (var i=0;i<7;i++)
{
if (odd(input)){
localvar++;
}
shr input;
}
return localwar;
}else return 0;
 }
`

**Comment by edemaine** [comment] 2017-11-23 12:54
To be clear, `\text{測試}` works fine (with any CJK character); it's just `測試` in math mode that doesn't work.  I don't see any particular reason to forbid CJK characters in math mode, so we should look at adding support for that.

**Comment by edemaine** [comment] 2017-12-12 20:35
FYI, PR #992 adds support for CJK characters in math mode.  We're still resolving some accent-related issues there.  If they don't get resolved soon (or the PR gets rejected), I could split off the CJK-in-math-mode part into a separate PR.

**Comment by rwbarton** [comment] 2018-01-08 18:22
It looks like #992 was merged, but without the math mode CJK support; what's the status of this?

**Comment by Lin-Buo-Ren** [comment] 2018-01-08 18:33
The issue can still be reproduced via the instruction atop, I guess #992 isn't enables it ATM

**Comment by edemaine** [comment] 2018-01-08 18:37
The status is issue #1046. I'd appreciate your input on that -- is there a way to get this to work in LaTeX?

**Comment by rwbarton** [comment] 2018-01-08 18:59
I actually haven't used xelatex myself unfortunately--I came across the Zulip issue while investigating something reltaed (which was fixed already in another Unicode-related KaTeX PR).

**Comment by kevinbarabash** [comment] 2018-01-30 01:50
I'm going to close this as a duplicate of #1046.

**Closed by kevinbarabash** 2018-01-30 01:50 UTC
Labels: Unicode, duplicate, enhancement

**Comment by edemaine** [comment] 2018-04-09 13:11
@tanjhysj0 On the master branch, you can set the `unicodeTextInMathMode` to `true`, and this should work.
