### ISSUE TITLE
Can't parse latex comments?

### ISSUE THREAD

**Issue by kindlychung** [Khan/KaTeX#384] opened 2015-11-09 12:41 UTC
Here is the error:

Uncaught ParseError: KaTeX parse error: Unexpected character: '%' at position 0: ̲%

**Comment by kevinbarabash** [comment] 2015-11-09 16:24
Duplicate of https://github.com/Khan/KaTeX/issues/20.

**Closed by kevinbarabash** 2015-11-09 16:24 UTC
