### ISSUE TITLE
Euro Symbol

### ISSUE THREAD

**Issue by Joe312341** [Khan/KaTeX#513] opened 2016-07-29 18:54 UTC
Hello,

I looked at some of the discussion in this repository..am I correct to assume that at this point the Euro symbol is not supported in any way?

Thanks

**Comment by kevinbarabash** [comment] 2016-07-29 21:46
That is correct.  Closing as a duplicate of https://github.com/Khan/KaTeX/issues/254.

**Closed by kevinbarabash** 2016-07-29 21:46 UTC
