### ISSUE TITLE
0.7.0 no dist folder

### ISSUE THREAD

**Issue by ymakhloufi** [Khan/KaTeX#613] opened 2017-01-09 15:52 UTC
When pulling in katex 0.7.0 via bower, I don't get a dist-folder but only a bower.json file in the bower_components/katex/ folder. Even when I remove it and pull it in as a sub dependency of angular-katex it is the same result. Why could that be?

**Comment by gagern** [comment] 2017-01-09 17:48
OK, this has been reported before, in #240 which got closed as a duplicate of #114. That one was aimed to address both bower and npm, and got fixed with #436 closing the npm half of the issue. The bower problem apparently remains open. @spicyj do you agree with this analysis?

Bower 1.8.0 reports this for me:

```
bower install katex
bower not-cached    https://github.com/Khan/KaTeX.git#*
bower resolve       https://github.com/Khan/KaTeX.git#*
bower download      https://github.com/Khan/KaTeX/archive/v0.7.0.tar.gz
bower extract       katex#* archive.tar.gz
bower invalid-meta  for:…/bower.json
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field cannot contain minified files
bower resolved      https://github.com/Khan/KaTeX.git#0.7.0
bower install       KaTeX#0.7.0

KaTeX#0.7.0 bower_components/KaTeX
```

That tarball is a *source* archive, so it doesn't contain `dist`, nor should it. The error messages are something else but shouldn't be too severe.

**Comment by ymakhloufi** [comment] 2017-01-09 18:03
Well it appears as if pulling in v0.6.0 with bower works, only from v0.7.0 ist is a problem, but since we need the support for umlaut characters, that is not an option...

**Comment by zeitgeist87** [comment] 2017-01-09 23:42
I have the exact same issue. Bower 1.8.0 reports this:

```bash
node_modules/bower/bin/bower install -V
bower katex#*               not-cached https://github.com/Khan/KaTeX.git#*
bower katex#*                  resolve https://github.com/Khan/KaTeX.git#*
bower katex#*                 download https://github.com/Khan/KaTeX/archive/v0.7.0.tar.gz
bower katex#*                  extract archive.tar.gz
bower katex#*             invalid-meta for:/tmp/andreas/bower/f1a02a1ae7fa47b237f875a1e98ba21e-7732-wZegpf/bower.json
bower katex#*             invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower katex#*             invalid-meta The "main" field cannot contain minified files
bower katex#*             invalid-meta The "main" field cannot contain minified files
bower katex#*                 resolved https://github.com/Khan/KaTeX.git#0.7.0
bower katex#*                  install katex#0.7.0

katex#0.7.0 bower_components/katex
```

After that the directory `./bower_components/katex/` contains only `bower.json`.

**Comment by ymakhloufi** [comment] 2017-01-10 06:59
Exactly the same for me. 

When I compare the two tar balls of 0.6.0 and 0.7.0, I can see that v0.6.0 does have a dist folder in it, where as the 0.7.0 doesn't...

https://github.com/Khan/KaTeX/archive/v0.7.0.tar.gz
vs.
https://github.com/Khan/KaTeX/archive/v0.6.0.tar.gz

**Comment by gagern** [comment] 2017-01-10 08:45
https://github.com/Khan/KaTeX/issues/114#issuecomment-271398964 has an analysis of what went wrong. Main reason is that I didn't consider bower in #546, where I added `dist` to `.gitignore` to avoid warnings about that directory during development. #615 aims to fix this, and personally I'd suggest creating a 0.7.1 release to add bower support.

**Comment by ymakhloufi** [comment] 2017-01-11 14:20
@gagern Thanks a lot for you lightspeed rection. Much appreciated!

**Comment by gagern** [comment] 2017-01-22 01:14
I released v0.7.1 which has a `dist` folder again. I have been able to use it with bower.

**Closed by gagern** 2017-01-22 01:14 UTC

**Comment by zeitgeist87** [comment] 2017-01-22 07:41
I can confirm that v0.7.1 solves the problem. Thanks!

**Comment by ymakhloufi** [comment] 2017-03-09 15:23
Yup, all good now.
