### ISSUE TITLE
\underset and exponent

### ISSUE THREAD

**Issue by pzinn** [Khan/KaTeX#1275] opened 2018-04-28 16:16 UTC
in KaTeX, 
```
\underset{*}{x}^2
```
results in the exponent 2 being right above x (instead of above to the right in LaTeX).
is that a known/expected behavior?

**Comment by kevinbarabash** [comment] 2018-04-28 19:56
We must be assuming that any character inside `\underset` should be typeset using the limits structure.  Looks like a bug.  Thanks for reporting.

**Comment by ronkok** [comment] 2018-04-28 21:30
@kevinbarabash I can confirm that `\underset` and `\overset` both use the limits structure. However, `\stackrel` is done differently and apparently in a more robust manner. I'll see if I can extend the `\stackrel` method to `\underset` and `\overset`.

**Comment by ronkok** [comment] 2018-04-28 22:42
@pzinn I just turned in PR #1277, which will fix this issue.

**Comment by edemaine** [comment] 2018-05-04 13:26
Fixed by #1277. Thanks for the report!

**Closed by edemaine** 2018-05-04 13:26 UTC
Labels: bug
