### ISSUE TITLE
Square root sign

### ISSUE THREAD

**Issue by HStaaf** [Khan/KaTeX#511] opened 2016-07-24 12:12 UTC
Square root signs do not look good. They are broken at one point (see attachement) and when written in the denominator of a fraction they are too close to the fraction line (see attachement)

![sqrt](https://cloud.githubusercontent.com/assets/8419394/17083706/92aaedca-51a8-11e6-84c7-25d59b6123d5.png)

**Comment by kevinbarabash** [comment] 2016-07-25 03:04
@HStaaf we're aware of the issue, but do unfortunately do not have fix.  Closing in preference of https://github.com/Khan/KaTeX/issues/60.

**Closed by kevinbarabash** 2016-07-25 03:04 UTC

**Comment by HStaaf** [comment] 2016-07-25 10:06
Shoot :( can it be mitigated by just increasing the font size perhaps?

**Comment by kevinbarabash** [comment] 2016-07-26 03:00
Unfortunately, it's not super high on priority.  I think the fix for this will be to render to SVG  because I think the browser doesn't handle sub-pixel position of elements which accumulates and results in these off-by-a-few-pixel rendering errors.  I haven't confirmed this so I'd want to do that before putting in a lot of work for a "relatively" small issue.  That being said, this rendering issue bugs me too.

**Comment by spicyj** [comment] 2016-07-26 03:03
@HStaaf To be clear, you can bump up the font size if you want! It takes the size from the surrounding text but you can probably also add a `.katex { font-size: 1.5em; }` stylesheet or similar.

**Comment by HStaaf** [comment] 2016-07-26 07:23
@spicyj one last question. Is there a font size that is considered optimal for rendering katex?

**Comment by spicyj** [comment] 2016-07-26 07:26
None officially. Try different sizes and see what works for you.
