### ISSUE TITLE
Completely sans-serif math

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#257] opened 2015-06-19 07:55 UTC
If a web page is written completely using sans-serif fonts, it would be nice if the math could match that aspect of the font. So I'd like for KaTeX to have a configuration where it produces sans-serif math.

I know that sans-serif formulas are really hard to achieve even in LaTeX. [This (German) survey](http://milde.users.sourceforge.net/Matheschriften/matheschriften.html#sans-serif-grotesk) has several suggestions there, non of which is perfect. Looking at that, I'd guess that porting [`arev`](http://ctan.org/pkg/arev) should be easiest and produce results which are particularly well suited to screen rendering. And it would integrate well with pages typeset in Vera Sans or DejaVu Sans, of which I believe there are quite a few.

Of course, one could first check whether the `KaTeX_SansSerif` fonts (which are apparently shipped but never used) are up to the task.

While the title of this question asks for “*completely* sans-serif math”, I believe that having some few symbols, like e.g. sum and integral operators, from another font is acceptable. The wording was chosen to distinguish this from supporting individual sans-serif symbols (using e.g. `\mathsf`) while keeping the default with serifs.

**Comment by spicyj** [comment] 2015-06-19 07:59
Going to count this as a duplicate of #123. We should figure this out though if we can. Not sure off the top of my head if there are good sans-serif Xe(La)TeX fonts but if there are that may be an easier route.

**Closed by spicyj** 2015-06-19 07:59 UTC
