### ISSUE TITLE
Parse error on --

### ISSUE THREAD

**Issue by cbreeden** [Khan/KaTeX#561] opened 2016-11-13 22:11 UTC
I haven't tried a git clone or anything, but <https://khan.github.io/KaTeX/> gives me a parse when I input `--`.

Input: `x--1`.  
Expected result: equivalent to `\displaystyle\mathord{x}\mathop{-}\mathord{-}\mathord{1}`.
Actual Result: `Uncaught Error: KaTeX parse error: Expected '}', got '--' at position 17: isplaystyle{x--̲1}`

**Comment by xymostech** [comment] 2016-11-13 22:14
Duplicate of #433 I think?

**Comment by cbreeden** [comment] 2016-11-13 22:14
I think so, sorry! Github doesn't play well while searching for "--" :)

**Closed by xymostech** 2016-11-13 22:14 UTC

**Comment by xymostech** [comment] 2016-11-13 22:17
:) No problem. Thanks for reporting!
