### ISSUE TITLE
border-spacing breaks sqrt-line placement

### ISSUE THREAD

**Issue by Loginisalreadytaken** [Khan/KaTeX#177] opened 2014-12-23 14:31 UTC
<div class="tex" data-expr="\sqrt{8}"></div>

If the above expression is placed in a table cell where border-spacing is not 0, sqrt-lines (and possibly other objects) are placed too high by the border-spacing value. This property is inherited but should have no effect here.

I tried different settings for vertical-align – they made no difference.

This goes for both FF30 and IE9 with identical results.

**Comment by kevinb7** [comment] 2015-05-25 01:56
@Loginisalreadytaken can you provide the code and a screenshot for this issue?

**Comment by PeterBocan** [comment] 2015-05-25 10:04
Well, sqrt-line placement is broken for me too. No matter what browser I use, the line is too low and, to be honest, that thing annoys me.

**Comment by kevinb7** [comment] 2015-05-25 15:29
It's a tough problem.  There's been a couple of suggested fixes, but none seem to be a complete fix.  It difficult because it's not only browser and OS specific, but ti's also font size specific.  It looks fine on Firefox on Mac OS X.  In the past I've tested it on all of the Windows browsers and it doesn't look good in any of them.

**Comment by kevinbarabash** [comment] 2015-12-23 01:54
I'm closing this a duplicate of https://github.com/Khan/KaTeX/issues/60.  @Loginisalreadytaken please re-open if this is not the case.

**Closed by kevinbarabash** 2015-12-23 01:54 UTC
