### ISSUE TITLE
wrong display of equal sign with 0.1.1

### ISSUE THREAD

**Issue by jeromew** [Khan/KaTeX#160] opened 2014-10-28 15:18 UTC
Hello,

I have a very simple command that I want to display : 

    \displaystyle{f(x) = g(x)}

the '=' symbol is shown, but the upper dash is nearly invisible. This does not happen on http://khan.github.io/KaTeX/

1/ I checked that all the requested fonts are loaded and everything looks ok.

2/ if I directly use http://khan.github.io/KaTeX/lib/katex/katex.min.css in my code, the '=' sign is shown correctly but google chrome warns about Font from origin 'http://khan.github.io' has been blocked from loading by Cross-Origin Resource Sharing policy ; It seems to say that when no fonts are loaded, the '=' sign is correct

3/ all the files seem identical between what I serve and what is served by http://khan.github.io/KaTeX

4/ if I directly use "//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.1.1/katex.min.css" in my code, the '=' sign is not shown correctly.

5/ if I refuse to serve the font files (404) then the '=' sign is correct again.

Have you ever hit this problem and do you have any advice on this ?

I don't understand why the problem does not appear on http://khan.github.io/KaTeX/

**Comment by kevinb7** [comment] 2015-06-19 06:22
@jeromew I'm going to close this as duplicate of https://github.com/Khan/KaTeX/issues/248 even though you reported this issue first, mainly because @spicyj has proposed a potential solution to the poor rendering quality in that issue.

**Closed by kevinb7** 2015-06-19 06:22 UTC

**Comment by jeromew** [comment] 2015-06-19 07:54
@kevinb7 ok no problem ; thanks for the issue triage ; the visual effect I had is indeed the same as on #248
