### ISSUE TITLE
a bit complex demo, failed....

### ISSUE THREAD

**Issue by mobilesolution2016** [Khan/KaTeX#627] opened 2017-01-15 15:23 UTC
```tex
\begin{array}{*{20}{c}}
1&3&\Theta \\
{\frac{{dy}}{{dx}}}&{\mathop {\lim }\limits_{\delta x \to 0} }& \pm \\
{\sum\limits_1^3 2 }&x& \ne 
\end{array}\theta
```

above code copy from MathType, its cannot render....

**Comment by gagern** [comment] 2017-01-15 15:36
KaTeX doesn't yet support the repeated column description `*{20}{c}`. It's one of the issues tracked by #269. As you are only using three columns, writing `ccc` instead would work well enough. Support for `\mathop` is a recent addition; in case you're still using KaTeX 0.6.0 (as we have CDN issues with 0.7.0), you might want to omit that, too. The following works on https://khan.github.io/KaTeX/:

```tex
\begin{array}{ccc}
1&3&\Theta \\
{\frac{{dy}}{{dx}}}&\lim_{\delta x \to 0}& \pm \\
{\sum\limits_1^3 2 }&x& \ne 
\end{array}\theta
```

I think I'll consider this a duplicate of #269.

**Closed by gagern** 2017-01-15 15:36 UTC
Labels: duplicate
