### ISSUE TITLE
Square root overbar is position below top of radical symbol "leg"

### ISSUE THREAD

**Issue by jwmerrill** [Khan/KaTeX#40] opened 2014-09-15 20:08 UTC
![image](https://cloud.githubusercontent.com/assets/48409/4277932/63382afe-3d13-11e4-855e-60b30e297e10.png)

Output on right is from latex for comparison. In KaTeX, a small "nub" appears at one of the joints in the square root symbol. I'm on OS 10.9.4 and I see this issue in both Chrome and Firefox.

**Comment by gagern** [comment] 2015-07-01 07:24
> I'm in the process of figuring out how to run the huxley tests.

With #264 in place, you get screenshots at least for Chrome on Linux. The corresponding test case snapshot demonstrates the issues discussed here, alkthough to a lesser degree I'd say:

![Sqrt-chrome.png](https://raw.githubusercontent.com/gagern/KaTeX/dd4304227962d78b9ee37ebb05c106cecb26606b/test/screenshotter/images/Sqrt-chrome.png)

**Comment by kevinbarabash** [comment] 2017-07-03 03:55
Closing this as a duplicate of https://github.com/Khan/KaTeX/issues/60.

**Closed by kevinbarabash** 2017-07-03 03:55 UTC
Labels: bug, rendering
