### ISSUE TITLE
hi  I want use sqrt [] but it still not support, I found other issue about this but do not work? 

### ISSUE THREAD

**Issue by monokeroslun** [Khan/KaTeX#244] opened 2015-06-10 08:38 UTC
hi  I want use sqrt [] but it still not support, I found other issue about this but do not work?  could you help me ?

**Comment by akkatracker** [comment] 2015-06-10 09:16
It's working for me:

    \sqrt{342}

Yields the square root of 342

**Comment by spicyj** [comment] 2015-06-10 17:31
Dupe of #48. Should work in the next release.

**Closed by spicyj** 2015-06-10 17:31 UTC
