### ISSUE TITLE
Support for \left.\middle/\right. (adjustable fraction signs)

### ISSUE THREAD

**Issue by HStaaf** [Khan/KaTeX#515] opened 2016-08-03 11:30 UTC
Are you considering adding support for fraction signs that adjust depending on the numerator and denominator. In LaTex the syntax is \left.\middle/\right.

![division](https://cloud.githubusercontent.com/assets/8419394/17364042/21d7ac18-597e-11e6-9d24-8383bebe12d2.png)

**Comment by sthoch** [comment] 2016-09-20 12:55
This is a duplicate of #527 (or the other way around).

**Comment by kevinbarabash** [comment] 2016-09-21 06:50
Even though this issue came in first, I'm going to close it as duplicate of https://github.com/Khan/KaTeX/issues/527.

**Closed** 2016-09-21 06:51 UTC
