### ISSUE TITLE
Break/wrap formula if too wide

### ISSUE THREAD

**Issue by scaljeri** [Khan/KaTeX#327] opened 2015-08-10 15:08 UTC
Is there a way to break formula's if they are to wide (with respect to their parent) ?

**Comment by spicyj** [comment] 2015-08-10 15:59
Not currently, but I was talking to @xymostech and the rules sound simple (breaking is allowed after any top-level rel or bin) so it might not be too difficult to add.

**Comment by scaljeri** [comment] 2015-08-10 18:32
+1 I really need this feature. Is `responsiveness` also included in the equation ?

**Comment by spicyj** [comment] 2015-08-10 18:32
I don't know what you mean by that, sorry?

**Comment by scaljeri** [comment] 2015-08-10 18:36
For example, if you switch from landscape to portrait, the `formula` adjusts to the space it has (responsive)

**Comment by invkrh** [comment] 2016-04-01 14:22
I think responsiveness is a big problem here.
Formules viewed from mobile break all responsive design.
They are too long, the view point is auto scaled to adapt these formulas.
I can not shorten the width of the formulas by setting width to a smaller value.
Really want to know any workaround.

**Comment by mbourne** [comment] 2016-04-02 05:48
@invkrh: Some possibilities until responsiveness becomes a feature in KaTeX:

(1) Give the enclosing element a style of "`overflow:auto`". Then your math will be full size and users can scroll the equation left and right to see it all.

For me, this has serious drawbacks, since on most mobile devices there is no indication that the element can be scrolled horizontally (no horizontal scrollbar appears like you get on a desktop browser, until you actually start scrolling the element. So if the page edge comes at an awkward part of the equation, it's possible the user has no idea that scrolling is possible and will never see the hidden part. It's possible to add a horizontal scroll bar with javascript of course).

Another option is display:table
http://netdna.webdesignerdepot.com/uploads7/how-to-create-horizontal-scrolling-using-display-table-cell/table-layout-horizontal/

(2) What I do is

(a) Manually break the equation into pieces at logical places (like equal signs, plus signs, minus signs, etc) so it will wrap logically

(b) For cases where splitting the equation is not possible, (it's a fraction, say), I nudge the font-size down with javascript until it does fit. I get away with that most of the time with the content on my site.

You can see both these things going on in this page (including in the drop-down answer sections):

http://m.intmath.com/fourier-series/2-full-range-fourier-series.php

The elements that cannot be split and that I know will not fit into a 300 px width are given the class "fitToWidth". The function "fitWidth" reduces the font-size if required.

I know it's clunky and could be done better (including the addition of an onRotate handler), but that will need to wait until the next revamp.

For the mobile version of my site, I mostly lay things out vertically when the LHS of an equation is quite wide.

Hope it helps.

Regards
Murray

**Comment by invkrh** [comment] 2016-04-02 22:12
@mbourne 
Thank you for the idea using the horizontal scroll bar and overflow.
The workaround really works.
Looking forward to the responsiveness of Katex. =)

**Comment by jeffswt** [comment] 2017-04-04 03:18
This would only line break inline equations and make displayed equations scroll.

Took me a while to figure it out, but you may simply copy this into the CSS file.

```CSS
.katex-display > .katex {
  display: inline-block;
  white-space: nowrap;
  max-width: 100%;
  overflow-x: scroll;
  text-align: initial;
}
.katex {
  font: normal 1.21em KaTeX_Main, Times New Roman, serif;
  line-height: 1.2;
  white-space: normal;
  text-indent: 0;
}
```

**Comment by kevinbarabash** [comment] 2017-04-16 00:32
@invkrh we ended adding a wrapper around each equation that would scale to fit and then if the user tapped it would zoom to the normal size and would allow the user to scroll within the container.  It wouldn't not cause the width of the page to expand.  The scrolling part is what @jeffswt has suggested.  The zooming/scrolling are both workarounds for not being able to break long expressions.

**Comment by hagenw** [comment] 2017-12-03 00:04
In principle the proposed css resolution works. I'm using the following at the moment:
```css
.katex-display > .katex {
    max-width: 100%;
}
.katex-display > .katex > .katex-html {
    max-width: 100%;
    overflow-x: auto;
    overflow-y: hidden;
    padding-left: 2px;
    padding-right: 2px;
}
```
But it can lead to some unwanted consequences.
Normal screen size:
![normal](https://user-images.githubusercontent.com/173624/33520978-221da48e-d7bd-11e7-9406-b6da8363bfe0.png)
Small screen size with overflow scrolling:
![responsive](https://user-images.githubusercontent.com/173624/33520993-7cb1c5c4-d7bd-11e7-95d9-ae25b7065f61.png)

**Comment by edemaine** [comment] 2017-12-03 18:40
@hagenw That's more likely to do with #824.

**Comment by edemaine** [comment] 2017-12-17 19:12
LaTeX supports automatic line breaking *for inline math*.  Here are some experiments:

```latex
Here is a long line of text.
Here is a long line of text.
Here is a $x+y+z+w+a+b+c$. % auto breaks after z+

Here is a long line of text.
Here is a long line of text.
Here is a $xyzabcdefghijklmnopqrstuvwxyz$.  % doesn't auto break

Here is a long line of text.
Here is a long line of text.
Here is a $xyzabcdefghij\allowbreak klmnopqrstuvwxyz$.  % auto breaks at \allowbreak
```

![line break demo](https://user-images.githubusercontent.com/2218736/34071511-3ef1ef56-e245-11e7-8bc5-ed9442c4a927.png)

In my opinion, this aspect would be super useful, and is might be what was originally requested.  We should try to implement it, with proper line breaking rules (only after ops?).

**Comment by SamLau95** [comment] 2018-01-16 22:28
We'd like to replace MathJax with KaTeX for a probability textbook at Berkeley: https://textbook.prob140.org/

The line breaking issue is currently a blocker for us since we've already written a bunch of long equations that KaTeX cuts off, for example:

![](https://user-images.githubusercontent.com/1305729/34920566-9a38418a-f929-11e7-897c-8d0eb31852e1.png)

We are currently using MathJax's automatic line breaking functionality (http://docs.mathjax.org/en/latest/output.html#automatic-line-breaking) which gives a reasonable-looking output for these cases:

![](https://user-images.githubusercontent.com/1305729/34929352-35e1cb4e-f978-11e7-8b65-679f3df82e63.png)

We can get around this with using:

```css
.katex {
  white-space: normal;
}
```

Which gives:

![](https://user-images.githubusercontent.com/2468904/35015206-2b03adcc-fac8-11e7-87da-4c09bd08e61f.png)

As you can see, this doesn't produce great output.

It would be great for us if KaTeX could support a rendering option like MathJax's that breaks long block-level equations in a reasonable way.

**Comment by ItsMeSousuke** [comment] 2018-04-19 13:32
Is there any progress with breaking lines for too wide formulas?

**Comment by kevinbarabash** [comment] 2018-04-22 00:04
@ItsMeSousuke not that I'm aware of.

**Comment by edemaine** [comment] 2018-05-04 15:53
#1287 is a first stab at doing line breaks for **inline** math (not display math). Testing would be appreciated!

**Comment by edemaine** [comment] 2018-05-11 19:10
PR #1287 is merged; feel free to test it out on the master branch.  So the inline case is done.  I'm going to close this issue, as issue #1023 covers the display case (in my opinion -- feel free to make alternate proposals if you'd like).

**Closed by edemaine** 2018-05-11 19:10 UTC
Labels: enhancement

**Comment by ccorcos** [comment] 2019-04-26 00:40
This CSS does a good job for me:

```css
.katex > .katex-html {
	white-space: normal;
}

.katex .base {
	margin-top: 2px;
	margin-bottom: 2px;
}
```

**Comment by hanzhihua72** [comment] 2019-07-17 05:55
The overflow solution sometimes also annoyingly cuts off equations when viewed in desktop

![image](https://user-images.githubusercontent.com/43427025/61350418-b0cc9f80-a824-11e9-8ea7-e553d4f21453.png)

To get around this, it might be better to wrap the css so that it is mobile only:

```
@media only screen and (max-width: 600px) {
  .katex-display > .katex {
    max-width: 100%;
    overflow-x: auto;
    overflow-y: hidden;
  }
}
```

**Comment by MicroDroid** [comment] 2019-11-22 20:48
This may **not** work for you but here:

```CSS
.katex {
	white-space: normal;
}

.katex .katex-html {
	overflow-wrap: normal;
}

.katex .mord {
	display: inline-block;
}
```

**Comment by Varun-msd** [comment] 2020-10-26 11:12
> This would only line break inline equations and make displayed equations scroll.
> 
> Took me a while to figure it out, but you may simply copy this into the CSS file.
> 
> ```css
> .katex-display > .katex {
>   display: inline-block;
>   white-space: nowrap;
>   max-width: 100%;
>   overflow-x: scroll;
>   text-align: initial;
> }
> .katex {
>   font: normal 1.21em KaTeX_Main, Times New Roman, serif;
>   line-height: 1.2;
>   white-space: normal;
>   text-indent: 0;
> }
> ```
> 
> Works perfectly on responsive pages, as far as I'm concerned.
> 
> Leave a like if you find this working nice.

What should I do if I break a displayed equation?

**Comment by q2apro** [comment] 2020-10-27 06:17
For the mobile layout and getting the horizontal scrollbar to show up, I have tried all proposed solutions above, without success. The horizontal scrollbar is still not showing up.

You might try it yourself over here: https://www.mathelounge.de/765244/wieso-konvergiert-a-n-1-1-n-n-gegen-0?show=765257#a765257

![image](https://user-images.githubusercontent.com/6764548/97263989-b1782200-182c-11eb-96d6-27246d06e7fb.png)

Both equations are wider than the screen, but the scrollbar stays invisible.

I have added this CSS:

```
	.katex-display {
		overflow-x: auto;
	}
	.katex-display > .katex {
		max-width: 100%;
		overflow-x: auto;
	}
```

Has something changed with Katex or is it maybe Chrome or something complete different? Thanks.

**Comment by mbourne** [comment] 2020-10-27 10:56
In your example, the scrollbars do appear once the user starts to scroll left-right.

To ensure the scrollbar stays visible all the time, you can use a class "overflowXauto" as follows:

<pre>.overflowXauto{
  display:block;
  height:auto;
  padding-bottom:12px;
  -webkit-box-sizing:border-box;
  overflow-x:auto;
  white-space:nowrap
}   
.overflowXauto::-webkit-scrollbar{
  height:8px
}
.overflowXauto::-webkit-scrollbar-track{
  -webkit-box-shadow:inset 0 0 4px rgba(0,0,0,0.3);
  border-radius: 7px
}
.overflowXauto::-webkit-scrollbar-thumb{
  border-radius:7px;
  -webkit-box-shadow:inset 0 0 8px rgba(0,0,0,0.5)
}
.overflowXauto::-webkit-scrollbar-thumb:hover{ 
  -webkit-box-shadow:inset 0 0 4px rgba(0,0,0,0.8)
}
</pre>

This ensures the user can see scrolling is possible. See it in action here (Method 1 formula):

https://www.intmath.com/counting-probability/10-bayes-theorem.php

![image](https://user-images.githubusercontent.com/7541940/97291966-94237200-1885-11eb-8fdd-9ecf87530740.png)

Hope it helps.
Murray

**Comment by Varun-msd** [comment] 2020-10-27 11:08
> In your example, the scrollbars do appear once the user starts to scroll left-right.
> 
> To ensure the scrollbar stays visible all the time, you can use a class "overflowXauto" as follows:
> 
> .overflowXauto{
>   display:block;
>   height:auto;
>   padding-bottom:12px;
>   -webkit-box-sizing:border-box;
>   overflow-x:auto;
>   white-space:nowrap
> }   
> .overflowXauto::-webkit-scrollbar{
>   height:8px
> }
> .overflowXauto::-webkit-scrollbar-track{
>   -webkit-box-shadow:inset 0 0 4px rgba(0,0,0,0.3);
>   border-radius: 7px
> }
> .overflowXauto::-webkit-scrollbar-thumb{
>   border-radius:7px;
>   -webkit-box-shadow:inset 0 0 8px rgba(0,0,0,0.5)
> }
> .overflowXauto::-webkit-scrollbar-thumb:hover{ 
>   -webkit-box-shadow:inset 0 0 4px rgba(0,0,0,0.8)
> }
> This ensures the user can see scrolling is possible. See it in action here (Method 1 formula):
> 
> https://www.intmath.com/counting-probability/10-bayes-theorem.php
> 
> ![image](https://user-images.githubusercontent.com/7541940/97291966-94237200-1885-11eb-8fdd-9ecf87530740.png)
> 
> Hope it helps.
> Murray

My question is not about displaying the scrollbars, I need to break the equation which is overflowing out of the screen (Automatic break) i.e in whatsoever the equation shouldn't go outside of the screen (Scroll should not take place)

**Comment by q2apro** [comment] 2020-10-27 11:43
Thanks Murray. 🙇‍♂️ 

So we need to wrap each equation into this self-defined CSS class `.overflowXauto`?

**Comment by mbourne** [comment] 2020-10-27 12:10
It needs to be a block-level element, so yes, wrap any expressions that (may) need a scroll bar into a DIV with that class.  You can make it skinnier if you want. The bottom padding was necessary because some KaTeX elements would be overlapped by the scroll bar without it.

**Comment by mbourne** [comment] 2020-10-28 01:38
@varun-msd; There is discussion on auto line-breaks earlier in this thread. See in particular https://github.com/KaTeX/KaTeX/issues/1023 , where it discusses what is already implemented in KaTeX.

**Comment by Varun-msd** [comment] 2020-10-28 10:30
<img width="379" alt="Screenshot 2020-10-28 at 3 58 02 PM" src="https://user-images.githubusercontent.com/71187534/97424214-677b6300-1936-11eb-8087-e4bf56304a31.png">
`Without equation, it is working as overflow: scroll

$Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)$

Without array it is working as expected (Breaking properly)
\begin{equation}
Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)
\end{equation}

With array and without equation (Not Breaking properly, overflow is scrolling)
$3Ta{n^{ - 1}}x$$=\left\{\begin{array}{ccc}
Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)
 \end{array}\right\}$

With array and with equation it is not working as expected (Curly braces has problem) - **THIS IS MY ISSUE**
$3Ta{n^{ - 1}}x$$=\left\{\begin{array}{ccc} \begin{equation}
Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right)Ta{n^{ - 1}}\left( {\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}} \right) \end{equation}
 \end{array}\right\}$
`

ISSUE: **Why if I add an equation inside an array it's breaking**?

**Comment by varunraghu3112** [comment] 2020-11-24 07:29
> In your example, the scrollbars do appear once the user starts to scroll left-right.
> 
> To ensure the scrollbar stays visible all the time, you can use a class "overflowXauto" as follows:
> 
> .overflowXauto{
>   display:block;
>   height:auto;
>   padding-bottom:12px;
>   -webkit-box-sizing:border-box;
>   overflow-x:auto;
>   white-space:nowrap
> }   
> .overflowXauto::-webkit-scrollbar{
>   height:8px
> }
> .overflowXauto::-webkit-scrollbar-track{
>   -webkit-box-shadow:inset 0 0 4px rgba(0,0,0,0.3);
>   border-radius: 7px
> }
> .overflowXauto::-webkit-scrollbar-thumb{
>   border-radius:7px;
>   -webkit-box-shadow:inset 0 0 8px rgba(0,0,0,0.5)
> }
> .overflowXauto::-webkit-scrollbar-thumb:hover{ 
>   -webkit-box-shadow:inset 0 0 4px rgba(0,0,0,0.8)
> }
> This ensures the user can see scrolling is possible. See it in action here (Method 1 formula):
> 
> https://www.intmath.com/counting-probability/10-bayes-theorem.php
> 
> ![image](https://user-images.githubusercontent.com/7541940/97291966-94237200-1885-11eb-8fdd-9ecf87530740.png)
> 
> Hope it helps.
> Murray

Sometimes overflow-x CSS which has Katex is creating some extra space on the right side after the block
![Screenshot 2020-11-24 at 12 58 14 PM](https://user-images.githubusercontent.com/37877365/100061934-d1fbc200-2e54-11eb-9b71-ec7071e936b5.png)
The hidden div creates the extra space

**Comment by mbourne** [comment] 2020-11-24 08:37
@Varun-msd For your first case, the equation environment is not implemented in KaTeX at this point in time. You can see what environments are available on this page: https://katex.org/docs/supported.html#environments

In LaTeX, trigonometric function names conventionally appear as all lower case, and non-italic. The following version is simpler and I think is close to what you want for that third example:

    3\tan^{-1}x=\begin{Bmatrix}
    \tan^{-1}\left({\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}}\right) &
    \tan^{-1}\left({\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}}\right) \\
    \tan^{-1}\left({\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}}\right) &
    \tan^{-1}\left({\cfrac{{3x - {x^3}}}{{1 - 3{x^2}}}}\right)
    \end{Bmatrix}

It looks like the following using the KaTeX demo page https://katex.org/

![image](https://user-images.githubusercontent.com/7541940/100068633-bdc6bd80-2e72-11eb-9bf1-be145b2c1e39.png)

For the second case, please provide a link to a minimal example (or a fiddle) so we can see what is going on.

Regards
Murray

**Comment by varunraghu3112** [comment] 2020-11-24 10:16
> > In your example, the scrollbars do appear once the user starts to scroll left-right.
> > To ensure the scrollbar stays visible all the time, you can use a class "overflowXauto" as follows:
> > .overflowXauto{
> > display:block;
> > height:auto;
> > padding-bottom:12px;
> > -webkit-box-sizing:border-box;
> > overflow-x:auto;
> > white-space:nowrap
> > }   
> > .overflowXauto::-webkit-scrollbar{
> > height:8px
> > }
> > .overflowXauto::-webkit-scrollbar-track{
> > -webkit-box-shadow:inset 0 0 4px rgba(0,0,0,0.3);
> > border-radius: 7px
> > }
> > .overflowXauto::-webkit-scrollbar-thumb{
> > border-radius:7px;
> > -webkit-box-shadow:inset 0 0 8px rgba(0,0,0,0.5)
> > }
> > .overflowXauto::-webkit-scrollbar-thumb:hover{
> > -webkit-box-shadow:inset 0 0 4px rgba(0,0,0,0.8)
> > }
> > This ensures the user can see scrolling is possible. See it in action here (Method 1 formula):
> > https://www.intmath.com/counting-probability/10-bayes-theorem.php
> > ![image](https://user-images.githubusercontent.com/7541940/97291966-94237200-1885-11eb-8fdd-9ecf87530740.png)
> > Hope it helps.
> > Murray
> 
> Sometimes overflow-x CSS which has Katex is creating some extra space on the right side after the block
> ![Screenshot 2020-11-24 at 12 58 14 PM](https://user-images.githubusercontent.com/37877365/100061934-d1fbc200-2e54-11eb-9b71-ec7071e936b5.png)
> The hidden div creates the extra space

@mbourne  any update on this issue ?

**Comment by mbourne** [comment] 2020-11-24 11:38
Yes, as I said at the end of my last reply, "For the second case, please provide a link to a minimal example (or a fiddle) so we can see what is going on."

**Comment by varunraghu3112** [comment] 2020-11-25 09:59
Screen record of issue: https://drive.google.com/file/d/1_AxpodIMRnZj9G7p9tyZK5cUwr2InOd5/view

CSS: 

.main-container {
  flex: 1;
  flex-direction: column;
  padding: 5px;
  padding-bottom: 0px;
  overflow-x: scroll;
  user-select: none;
}

table {
  display: block;
  overflow-x: scroll;
  background-color: pink
  box-sizing: border-box;
  border-collapse: collapse;
  margin-bottom: 20px;
}

td, th {
  border: 1px solid ${theme.textColor.regular};
  padding: 1.0rem;
  word-break: normal;
}


`
- Neutrons are discovered by **James Chadwick**. 
- It is neutral particle which is slightly heavier than proton
- When Beryllium bombarded by $\alpha-$ particles, neutrons formed.

	Example: 
	${}_4B{e^9} + {}_2H{e^4} \to {}_6{C^{12}} + \mathop {{}_0{n^1}}\limits_{\left( {neutron} \right)}$
	
|Particle (Scientist)| Symbol |Charge | Mass (amu /Kg)|
|--|--|--|--|
| Electrons (J.J.Thomson) | $- {1^{{e^0}}}$ or ${e^ - }$ | $- 1.6 \times {10^{ - 19}}C$ or $-4.8 \times {10^{ - 10}}$ esu| $0.000549/$$9.1\times {10^{ - 31}}$|
|Proton (Goldstein) |P or ${}_1{H^1}$ |$+ 1.602 \times {10^{ - 19}}C$ or $+4.8 \times {10^{ - 10}}$ esu| $1.00758/$$1.672\times {10^{ - 27}}$|
|Neutron (Chadwick) |${}_0{n^1}$ | Zero charged | 1.00893/$1.674\times {10^{ - 27}}$|
|Positron (Anderson) | ${}_{ + 1}{e^0}$ | 1 unit +Ve charge  | 0.000549/$9.1\times {10^{ - 31}}$|
|Neutrino and Antineutrino (Fermi) | ${}_0{e^0}$ | Zero charge | < 0.00002 |
|Antiproton (Chanberlain)| ${}_{ - 1}p$ |Negative charge | 1.00758 |
|Meson (Yukawa) | ${\pi ^ + },{\pi ^0},{\pi ^ - }$ | +Ve, zero, -Ve | 273 >${e^ - }$ |
`

**Comment by varunraghu3112** [comment] 2020-11-25 10:32
@mbourne **position: relative** solved the issue !

**Comment by arunkumaralagesan** [comment] 2021-01-12 09:36
> We'd like to replace MathJax with KaTeX for a probability textbook at Berkeley: https://textbook.prob140.org/
> 
> The line breaking issue is currently a blocker for us since we've already written a bunch of long equations that KaTeX cuts off, for example:
> 
> ![](https://user-images.githubusercontent.com/1305729/34920566-9a38418a-f929-11e7-897c-8d0eb31852e1.png)
> 
> We are currently using MathJax's automatic line breaking functionality (http://docs.mathjax.org/en/latest/output.html#automatic-line-breaking) which gives a reasonable-looking output for these cases:
> 
> ![](https://user-images.githubusercontent.com/1305729/34929352-35e1cb4e-f978-11e7-8b65-679f3df82e63.png)
> 
> We can get around this with using:
> 
> ```css
> .katex {
>   white-space: normal;
> }
> ```
> 
> Which gives:
> 
> ![](https://user-images.githubusercontent.com/2468904/35015206-2b03adcc-fac8-11e7-87da-4c09bd08e61f.png)
> 
> As you can see, this doesn't produce great output.
> 
> It would be great for us if KaTeX could support a rendering option like MathJax's that breaks long block-level equations in a reasonable way.

is it possible to reproduce how the mathjax is breaking the equations in katex, not especially through scroll?. Any help will be appreciated.

**Comment by ShaunDychko** [comment] 2022-10-04 22:26
https://github.com/KaTeX/KaTeX/issues/327#issuecomment-291382715 no longer works in katex version 0.16.2. For inline equations it needs to be adapted to
```css
.katex-html > .base {
  white-space: normal;
}
```

**Comment by ihsan6133** [comment] 2023-06-16 15:45
How to enable word wrap while working with mhchem, whitespaces do not break up into multiple lines in a \ce{} block,
