### ISSUE TITLE
Incorrect rendering of in \text enviroment

### ISSUE THREAD

**Issue by danielhollas** [Khan/KaTeX#1086] opened 2018-01-24 03:43 UTC
PR #1076 introduced more supported characters inside \text environment. However, some of them does not seem to bere rendered correctly. Specifically,
 - czech character ů (U+016F): circle above u is not properly centered
 - Turkish character İ (U+0130): the dot is not directly above the I

Below is the rendering of the following KaTex block by @davidflanagan :
$\text{\blue{इकाई}} \cdot
\text{\purpleD{egyenlő}} \cdot 
\color{red}{\text{větší než ř Původní}} \cdot
\green{\text{İı}}$

![image](https://user-images.githubusercontent.com/9539441/35313246-9b485d9c-00bf-11e8-85a4-05bdb9e5fb6a.png)

It might be worthwhile to check other similar letters in Latin Extended block A and B, but I do not have time and resources to do that,  unfortunately.

Thank you!

**Comment by kevinbarabash** [comment] 2018-01-24 03:49
@danielhollas we've had issues in general with positioning of accents in some browsers.  Safari doesn't handle combining glyphs properly.  Part of the solution is https://github.com/KaTeX/katex-fonts/pull/5 which converts all combining glyphs to non-combing glyphs.  There will probably be some additional work in this repo to make sure everything is positioned correctly after making that change.

**Comment by kevinbarabash** [comment] 2018-01-24 03:50
At least the Hindi is look good. :)

**Comment by danielhollas** [comment] 2018-01-24 03:59
Well, these two do not work on Chromium and Firefox on Linux Mint either.

PS:Hindi certainly looks cool, but I have no idea whether the render is correct. :smile:

**Comment by davidflanagan** [comment] 2018-01-24 07:10
It sounds like this is a duplicate of issue #1066 

Thanks for filing this Daniel, but let's move discussion over to that other bug.

**Comment by davidflanagan** [comment] 2018-01-24 07:11
Duplicate of #1066

**Closed by davidflanagan** 2018-01-24 07:11 UTC
