### ISSUE TITLE
devServer.app undefined in screenshotter.js when running on MacOS

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1082] opened 2018-01-23 05:19 UTC
I tried a fresh checkout and am still encountering the issue when running:
```
dockers/Screenshotter/screenshotter.sh --verify
```
or 
```
make screenshots
```
The error `TypeError: Cannot read property 'get' of undefined` occurs on KaTeX/dockers/Screenshotter/screenshotter.js:321:18.  It appears to be that `app` is not defined on `server`.  I'm not sure why the tests are passing on travis-ci.  

@ylemkimon could you have a look into this?

**Comment by ylemkimon** [comment] 2018-01-23 08:08
Are you using Mac? I wasn't able to reproduce the issue on Windows and Linux.

**Comment by kevinbarabash** [comment] 2018-01-23 13:02
@ylemkimon I am running on a Mac.  I tried a couple of different versions of `webpack-dev-server`: 2.7.1, 2.8.0, and 2.9.1.

**Comment by ylemkimon** [comment] 2018-01-23 16:58
On Mac, `katexIP` is set to `*any*` in `guessDockerIPs()`:
https://github.com/Khan/KaTeX/blob/732f2a84ccb000099d29fb1f61dd02e611fab64b/dockers/Screenshotter/screenshotter.js#L153-L158

This causes following lines to run in `findHostIP()`:
https://github.com/Khan/KaTeX/blob/732f2a84ccb000099d29fb1f61dd02e611fab64b/dockers/Screenshotter/screenshotter.js#L321

whereas on Windows and Linux, it doesn't reach above:
https://github.com/Khan/KaTeX/blob/732f2a84ccb000099d29fb1f61dd02e611fab64b/dockers/Screenshotter/screenshotter.js#L310-L317

The `devServer` is intended to be a `webpackDevServer` instance, which has an Express application as `app` property.

Instead, the return value of `webpackDevServer.listen()`, an instance of `http.Server`, was assigned to `devServer` in `startServer()`:
https://github.com/Khan/KaTeX/blob/732f2a84ccb000099d29fb1f61dd02e611fab64b/dockers/Screenshotter/screenshotter.js#L199-L202

This caused `TypeError: Cannot read property 'get' of undefined` on running the screenshotter on Docker for Mac.

I should've tested on the Mac, and apologize for any inconveniences it has caused.

**Closed by ylemkimon** 2018-01-23 16:58 UTC
Labels: infrastructure

**Comment by kevinbarabash** [comment] 2018-01-23 17:00
> I should've tested on the Mac, and apologize for any inconveniences it has caused.

No worries.  Thanks for tracking this down so quickly.
