### ISSUE TITLE
Triangles don't appear correctly

### ISSUE THREAD

**Issue by mbourne** [Khan/KaTeX#790] opened 2017-08-13 03:02 UTC
@kevinbarabash There seems to be a problem with swapped up and down triangles in the demo page.

![image](https://user-images.githubusercontent.com/7541940/29245765-e228d19e-8016-11e7-86e5-d867c7ab12a1.png)

\triangledown looks big, and \bigtriangleup looks small.

Also, left and right triangles look tiny. Are they meant to?

**Comment by kevinbarabash** [comment] 2017-08-13 03:08
I thought this was going to be an easy issue, but the glyphs aren't in the font which means we have to figure out which fonts they're in and then copy them over.

**Comment by kevinbarabash** [comment] 2017-08-13 17:24
I thought there was supposed to be a size difference between `\triangle` and `\bigtriangleup` but that isn't actually the case.

**Comment by kevinbarabash** [comment] 2017-08-13 17:26
The triangles look right on http://copyasmarkup.com/katex/function-support.html.

**Comment by edemaine** [comment] 2017-08-13 18:48
`fdsymbol` defines `\triangle` smaller than `\bigtriangleup` (but still bigger than `\triangleleft`).  See [symbols-a4, Table 135](http://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf#page=69).  So this issue depends on package use...  Personally, I'd be fine if we just made the `\bigtriangleup/down` bigger than they are now.  (We could even hack this now, by defining a macro `\bigtriangleup` &rarr; `\large\triangleup`.)

Reminds me to finally make issue #793 about listing packages that best reproduce KaTeX behavior.

**Comment by edemaine** [comment] 2017-08-13 18:52
I notice that `\triangle` is from the main font while `\triangledown` is from the ams font.  Perhaps this is related to @mbourne's original issue?

**Comment by ronkok** [comment] 2017-08-14 01:05
@mbourne I am responding to your question here, since this is now an issue of its own. I am baffled by your original screenshot, but I can help clarify some of the later questions.

The function support page does not run a KaTeX script for every one of its entries. On the symbol table, I just applied CSS `font-family: KaTeX_Main, KaTeX_AMS;` to the odd numbered columns and wrote in the correct character. I meant the page to be an informative tool, not a diagnostic tool.

I did a similar treatment to letters, operators, and relations. By so doing, the page runs several hundred fewer scripts. 

Just now, I have refreshed the [preview page](http://copyasmarkup.com/katex/function-support.html#symbols) and the six white triangles all *do* run a script. So @edemaine's observation about `\triangledown` is now visible. 

That doesn't explain @mbourne's original observation. He should have seen triangles all from the KaTeX-Main font and I can't explain that screenshot.

**Comment by kevinbarabash** [comment] 2017-08-16 02:37
It sounds like the original issue that @mbourne was seeing is gone now.  Is this safe to close?

**Comment by mbourne** [comment] 2017-08-16 03:08
It still seems to me that the first triangle is as big as the \bigtriangleup, but should be smaller like the size of \triangledown. However, that seems to be LaTeX behavior, so I guess we need to consider it solved.

![image](https://user-images.githubusercontent.com/7541940/29345622-8956853a-8272-11e7-8d1d-bbab79b90d8e.png)

**Comment by edemaine** [comment] 2017-08-16 13:27
Confirmed in LaTeX:

```latex
\usepackage{amsmath,amssymb}
\begin{document}
\begin{tabular}{ll}
$\triangle$ & \verb|\triangle| \\
$\triangledown$ & \verb|\triangledown| \\
$\triangleleft$ & \verb|\triangleleft| \\
$\triangleright$ & \verb|\triangleright| \\
$\bigtriangledown$ & \verb|\bigtriangledown| \\
$\bigtriangleup$ & \verb|\bigtriangleup|
\end{tabular}
```

![triangle](https://user-images.githubusercontent.com/2218736/29365413-eca7b77a-8264-11e7-95f3-e81e022d6a79.png)

It shows that we're using the AMS fonts. 😃 I wouldn't be adverse to switching to other (more logical) definitions of these symbols defined in other LaTeX packages, but it would be a major font effort, so closing this for now.  Thanks for the report, @mbourne!

**Closed by edemaine** 2017-08-16 13:27 UTC
