### ISSUE TITLE
Impossible to use katex bower dependency without build

### ISSUE THREAD

**Issue by ystreibel** [Khan/KaTeX#240] opened 2015-06-05 08:55 UTC
Hi,

After having pulled the katex dependency with bower. It appears that the katex.min.js is not present, nor the katex.min.css.

For other bower dependency, it is not required to launch a build script, it should be usable directly 'as is'.

**Comment by spicyj** [comment] 2015-06-05 08:55
Dupe of #114.

**Closed by spicyj** 2015-06-05 08:55 UTC
