### ISSUE TITLE
Dividing lines for \frac and overhead lines for \sqrt sometimes disappear

### ISSUE THREAD

**Issue by akalin** [Khan/KaTeX#824] opened 2017-08-27 18:02 UTC
When trying to upgrade to 0.8.x, I noticed that it sometimes omitted the dividing lines for \frac and the overhead lines for \sqrt.

Here's a test file showing the problem (for dividing lines): https://rawgit.com/akalin/60e78169d60908f8111652540f427607/raw/f53ae1650b12bf6db46b264e8852ded3d82ca7e7/test-0.8.2.html At default zoom, the dividing line for the \fracs in the 2nd expression isn't visible, and if you zoom in and out, you can make one or more of the lines disappear.

Here's the same file using 0.7.1: https://rawgit.com/akalin/60e78169d60908f8111652540f427607/raw/f53ae1650b12bf6db46b264e8852ded3d82ca7e7/test-0.7.1.html If you zoom out far enough, the lines do disappear, but it seems somehow more robust then 0.8.x.

I suspect that the problem isn't unique to 0.8.x, but the change in rendering the superscripts exposed it.

Gist for the test file using other versions: https://gist.github.com/akalin/60e78169d60908f8111652540f427607

**Comment by kevinbarabash** [comment] 2017-08-27 19:46
Fixed in #810.  See #799.  I'm going to leave this issue open until we publish a new version with the fix.

**Comment by kevinbarabash** [comment] 2017-08-27 19:50
I should mention that the #810 does not fix the fraction bar issue.  I have not been able to reproduce either issue.  @akalin what browser and OS versions are you using?

**Comment by akalin** [comment] 2017-08-27 20:00
I'm using Chrome Version 62.0.3192.0 (Official Build) dev (64-bit) on Linux and macOS. Just tried Safari 10.1.2 and Firefox 55.0.3 and  it works fine there. So it might be a Chrome-only issue, or even a dev-channel-only issue.

**Comment by akalin** [comment] 2017-08-27 20:03
Also works fine on Chrome Version 60.0.3112.101 (Official Build) (64-bit) on Windows.

**Comment by akalin** [comment] 2017-08-27 20:16
On Windows, works fine for Version 61.0.3163.59 (Official Build) beta (64-bit) but not Version 62.0.3192.0 (Official Build) dev (64-bit). So it looks like a dev-channel-only issue.

**Comment by kevinbarabash** [comment] 2017-08-27 22:08
The `\sqrt` issue is fixed in [v0.8.3](https://github.com/Khan/KaTeX/releases/tag/v0.8.3).

**Comment by akalin** [comment] 2017-08-27 22:42
Cool, looks like it works: https://rawgit.com/akalin/60e78169d60908f8111652540f427607/raw/d1d9228c76637ffd92b4af1d9fe75075fea15d30/test-0.8.3.html

Now it's just the missing fraction bar that's the problem.

**Comment by edemaine** [comment] 2017-08-28 18:41
Given our inability to reproduce, can you include a screenshot?  Any idea what changes are in Chrome dev-channel that might cause a change here?  Perhaps the rounding rules for subpixel resolution are changing?  (That would be unfortunate...)

**Comment by akalin** [comment] 2017-08-28 19:13
Okay, here are some screenshots at various zoom levels with 0.8.3 on macOS Chrome Version 62.0.3192.0 (Official Build) dev (64-bit).

<img width="493" alt="screenshot-0 8 3-50" src="https://user-images.githubusercontent.com/425576/29789229-40f3e1e4-8bea-11e7-8cba-8cee6fcba3d6.png">
<img width="524" alt="screenshot-0 8 3-67" src="https://user-images.githubusercontent.com/425576/29789230-40fbc3fa-8bea-11e7-8d4c-36db14f0dfbd.png">
<img width="541" alt="screenshot-0 8 3-80" src="https://user-images.githubusercontent.com/425576/29789232-41016828-8bea-11e7-845c-e6df5fcc752d.png">
<img width="583" alt="screenshot-0 8 3-100" src="https://user-images.githubusercontent.com/425576/29789231-41007904-8bea-11e7-8810-7ccdef024ebe.png">

**Comment by akalin** [comment] 2017-08-28 19:19
Here are some more screenshots with KaTeX 0.7.1 on macOS Chrome Version 62.0.3192.0 (Official Build) dev (64-bit).

<img width="551" alt="screen shot 2017-08-28 at 12 16 37 pm" src="https://user-images.githubusercontent.com/425576/29789485-122dabaa-8beb-11e7-9fb5-109253daa85c.png">
<img width="534" alt="screen shot 2017-08-28 at 12 16 41 pm" src="https://user-images.githubusercontent.com/425576/29789486-122ee3b2-8beb-11e7-86c6-4a10e6c407c7.png">
<img width="517" alt="screen shot 2017-08-28 at 12 16 42 pm" src="https://user-images.githubusercontent.com/425576/29789488-1240f73c-8beb-11e7-828a-95d5e194bab0.png">
<img width="493" alt="screen shot 2017-08-28 at 12 16 44 pm" src="https://user-images.githubusercontent.com/425576/29789489-12429650-8beb-11e7-9aee-fbd1e24be6b9.png">

**Comment by akalin** [comment] 2017-08-28 19:21
Also, when testing with Firefox 55.0.3 on macOS, I noticed that the sqrt overlines disappear at 30% zoom with 0.8.3, but work fine with 0.7.1, so unfortunately it seems like that isn't fully fixed yet, either.

**Comment by xsznix** [comment] 2017-09-07 03:45
Ah, I've run into the same issue on the version of KaTeX (0.8.1-ish, IIRC) that's currently on Messenger, even at default zoom:

![screen shot 2017-09-06 at 22 37 04](https://user-images.githubusercontent.com/1859825/30144957-f7e03ee6-9353-11e7-83ec-2db434e1327b.png)

It seems to be slightly evasive, and I'd help except I can't for the life of me figure out how to change the appearance of the `sqrt-line`…

**Comment by kevinbarabash** [comment] 2017-09-07 04:04
@xsznix what happens if you put the `\sqrt` in the denominator or have it outside of the fraction?

**Comment by xsznix** [comment] 2017-09-07 05:10
Outside a fraction, `$$\sqrt{b^2-4ac}$$` renders at first but if I scroll it out of view and then back it disappears.

In the denominator it seems fine:

![screen shot 2017-09-07 at 00 10 00](https://user-images.githubusercontent.com/1859825/30146967-eff4837e-9360-11e7-8569-fe591ce415ee.png)

**Comment by kevinbarabash** [comment] 2017-09-07 13:53
It looks like the `2` is clipped.  My guess is that the container that the math is being rendered into is too small.  @sophiebits what's a good way to report issues to the Messenger team?

**Comment by sophiebits** [comment] 2017-09-07 14:40
There's no good way for non-employees to reliably report bugs and get a response. CCing me here is fine. If someone wants to suggest a particular CSS change to Messenger that would be even better. ;)

**Comment by edemaine** [comment] 2017-09-07 14:45
I don't think this is particular to Messenger.  But no one has been able to track down the problem source or solution yet...  It doesn't help that most of us can't reproduce the problem.  My current suspicion is that this has to do with display DPI or something along those lines, so it's hard to reproduce.  @xsznix could you let us know your screen resolution, DPI, browser, OS?

**Comment by edemaine** [comment] 2017-09-07 14:49
Oops, sorry, reading more thoroughly, it does look like the container issue is particular to Messenger.  And I can reproduce it!

I just took a quick look, and Messenger CSS has `overflow-x: auto; overflow-y: hidden` set.  Removing *both* of these fixes the clipping.  Is there a security or other concern that causes you to include those?

**Comment by sophiebits** [comment] 2017-09-07 14:51
I blame @xsznix who wrote that code in Messenger this summer. :) It's designed to limit the width of expressions so you can scroll if they get too wide.

**Comment by edemaine** [comment] 2017-09-07 15:05
The main problem, I guess, is that the bounding box is somehow getting set wrong.  Because we don't normally limit `overflow`, we don't see this.  The strange thing is that I can't reproduce it in another KaTeX environment (like `make serve`), though the relevant CSS seems identical.

A simple example is `a^2+b^2=c^2`.  Looking at the inspector, the `vlist-t` containing the first superscript has a bounding box that is not tall enough.  But somehow the containing `msupsub` extends the top of the box to a good place in `make serve`, but not in Messenger, despite no apparent CSS to do so...  Perhaps someone familiar with `vlist` can understand this?

**Comment by sophiebits** [comment] 2017-09-07 16:43
On the KaTeX site, I can repro `a^{2^2}` going outside the bounding box…

![image](https://user-images.githubusercontent.com/6820/30174765-005c226c-93b1-11e7-8eff-7fb6e9506cc5.png)

**Comment by akalin** [comment] 2017-09-07 17:21
Are these the same bug or two separate bugs? Perhaps we should split the issues...

**Comment by xsznix** [comment] 2017-09-07 19:14
@edemaine I'm on Chrome 60, macOS 10.12.6, and the issue occurs at both 1x and 2x DPI scaling.

@sophiebits Adding `#facebook ._1e4d._3_3l .katex-display {padding: 1px 0}` seems to fix clipping on both the sqrt line and the nested superscript. Possibly worth sending over to the Messenger team? It's probably not the optimal solution but it sounds much easier than fiddling with vlists.

**Comment by edemaine** [comment] 2017-09-08 00:34
The fact that 1px of padding is enough suggests this has something to do with rounding?  Perhaps related to [this issue](https://stackoverflow.com/questions/34676263/sub-pixels-calculated-and-rendered-differently-among-browsers)...  I'd be curious to know if it's possible to get more than 1px error.  Maybe we should have a general rule of `.katex { padding: 1px 0px}`?

**Comment by sophiebits** [comment] 2017-09-08 02:58
We opted to add the 1px padding to Messenger for now. Reload and you should see it.

**Comment by kevinbarabash** [comment] 2017-09-16 20:14
In #312, @xymostech pointed out that we make our fonts thicker and so our font metrics should be adjusted.  Fixing this may address the core of the problem.  The downside of fixing the metrics is that it will probably make our output deviate more for LaTeX's output.

**Comment by mbourne** [comment] 2017-09-27 04:36
I'm also facing the disappearing fraction lines issue, inconsistent across browser versions and even within a document.

**Browser:** Chrome Version 61.0.3163.100 (Official Build) (64-bit)
**OS:** Win7
**KaTEX version:** 0.8.3
**Example page:** https://www.intmath.com/forum/applications-integration-30/a-simple-integration:140#pid845

One of the fractions in the last forum entry of that page looks like this:

![image](https://user-images.githubusercontent.com/7541940/30895140-d3959c7a-a37a-11e7-9be3-721ec853eda9.png)

However, a bit higher up the page, the fraction line is fine but the generated code is identical, and there are no differences in the style for any of the surrounding divs.

![image](https://user-images.githubusercontent.com/7541940/30895115-abd3e098-a37a-11e7-8a05-389802659904.png)

I can't find any reason why they render differently (it's not because of the equal sign).

My default font size for class .katex is 1.15 em, which gives me a resulting 18.4px font (which does show the problem).

If I set .katex at exactly 18px, it's fine, but at 18.1px, the line doesn't show, nor at exactly 18.4px. At other nearby values, the result is:

17.8px: fails
17.9px: fails
18.01px, 18.02px, 18.03px: shows
18.04px: fails
18.2px: shows
18.3px: shows
18.5px: shows

On the other hand:

**Browser:** Chrome: Version 60.0.3112.113 (Official Build) (64-bit)
**OS:** Win 10

The fraction lines are all fine in this combination.

**Comment by kevinbarabash** [comment] 2017-09-27 05:15
Both of the screenshots below were taken on a retina screen.  Even though the sizes of the images are different the relative width of the fraction bar compared to the width of the lines in the equal sign should be the same.  It looks like the KaTeX rendering of the fraction bar is not as thick as it should be. 

khan.github.io/KaTeX
<img width="102" alt="screen shot 2017-09-26 at 11 06 36 pm" src="https://user-images.githubusercontent.com/1044413/30896720-88df1410-a30f-11e7-86af-2e7037d4b311.png">

pdflatex:
<img width="135" alt="screen shot 2017-09-26 at 11 06 24 pm" src="https://user-images.githubusercontent.com/1044413/30896711-82d5b452-a30f-11e7-98fb-d9d911653113.png">

**Comment by kevinbarabash** [comment] 2017-09-27 05:30
This is what's currently on `master` (with `displayMode: true`).  You'll notice that the fraction bar is much thicker and matches what pdflatex is doing.  I'll do a release tomorrow and hopefully that will fix this issue.
<img width="197" alt="screen shot 2017-09-26 at 11 27 44 pm" src="https://user-images.githubusercontent.com/1044413/30897226-560a0b8c-a312-11e7-90e5-c1c9963167b7.png">

**Comment by akalin** [comment] 2017-09-28 21:36
Is there anything else blocking a new release? Would love to test!

**Comment by mbourne** [comment] 2017-09-30 12:40
The disappearing fraction lines are still showing up for me on latest Chrome. It's still strange to me how the exact same fraction elsewhere on the page will be OK. I've seen this in a few places. The 0.04em fraction line thickness was not thick enough.

Until a new release, I'm doing the following post-processing which appears to work OK. Thought it may help others:

<pre>function thickenFracLines() {
	var fracs = document.getElementsByClassName("frac-line");
	for(k=0; fracs.length > k;k++) {
		fracs[k].setAttribute("style", "border-bottom-width:0.08em");
	}	
}
thickenFracLines();</pre>

**Comment by kevinbarabash** [comment] 2017-09-30 23:47
@akalin nothing's blocking the release other than I'm on vacation and busy seeing people.  The weather's supposed to be bad Monday so I'm spend some time doing the release then.

**Comment by mbourne** [comment] 2017-10-01 00:28
@kevinbarabash Your certainly deserve a holiday, Kevin! I don't know when you ever sleep...

**Comment by kevinbarabash** [comment] 2017-10-03 17:46
I tried to do a release this morning but ran into issues with the release script that I need to debug.

**Comment by kevinbarabash** [comment] 2017-10-06 03:44
I've resolved the issue and finished the release.  @akalin and @mbourne please give https://github.com/Khan/KaTeX/releases/tag/v0.9.0-alpha a try and see if that resolves this issue.

**Comment by kevinbarabash** [comment] 2017-10-06 03:46
To be clear... the release in my previous post should help with fraction bars disappearing, but does __not__ add any padding to address the radical bar disappearing issue.

**Comment by akalin** [comment] 2017-10-06 04:52
Unfortunately, it looks like the auto-render extension is now broken? See https://rawgit.com/akalin/60e78169d60908f8111652540f427607/raw/73e1ae29425f621a700c7ccc7c561e118f7123b6/test-0.9.0-alpha.html

**Comment by akalin** [comment] 2017-10-06 04:54
...in that
```
renderMathInElement(document.body, {
  delimiters: [
    {left: "\\[", right: "\\]", display: true},
    {left: "\\(", right: "\\)", display: false}
  ],
  ignoredTags: [
    "script", "noscript", "style", "textarea", "pre", "code",
    // We sometimes need a dedicated tag.
    "nokatex"
  ]
});
```
doesn't work anymore.

**Comment by akalin** [comment] 2017-10-06 04:55
Seems like the auto-render extension is being webpacked into some new ES6 format, which probably isn't intended.

**Comment by rrandallcainc** [comment] 2017-10-06 09:29
Looking into this.

**Comment by rrandallcainc** [comment] 2017-10-06 18:23
@akalin Thanks for finding/digging into this. Please see the open PR: https://github.com/Khan/KaTeX/pull/920

**Comment by akalin** [comment] 2017-10-17 03:34
Here's a test page with the latest alpha: https://rawgit.com/akalin/60e78169d60908f8111652540f427607/raw/230b50fbf1f83fbf748b1683942620e6de21a69d/test-0.9.0-alpha1.html

Looks like it mostly works now! I still see disappearing fraction lines at 50% and lower zooms, but that's way better than before. Thanks!

**Comment by mbourne** [comment] 2017-11-09 06:06
I've been holding off until the next full release (not an alpha). But I tried 0.9.0-alpha locally yesterday, and I'm still seeing the fraction line problem, especially on dynamically generated math.

**Comment by kevinbarabash** [comment] 2017-11-12 03:17
@mbourne have you tried `0.9.0-alpha1` yet?  That's the release that has #931 which makes the issue better.

**Comment by mbourne** [comment] 2017-11-12 07:29
@kevinbarabash No I hadn't, and indeed it does!

**Comment by kkiningh** [comment] 2017-11-13 20:44
I'm using `0.9.0-alpha1` and I think I'm still seeing this issue. See the attached screenshot (100% zoom in Chrome on 15" Macbook Pro).

<img width="245" alt="screen shot 2017-11-13 at 12 41 19 pm" src="https://user-images.githubusercontent.com/360345/32748094-fe039b50-c86f-11e7-93e0-816155f8dde2.png">

**Comment by ronkok** [comment] 2017-11-17 05:41
@kevinbarabash I don't have a good explanation for why this is happening.  A 15" Macbook Pro is supposed to display at 220 dpi, according to [DPI love](http://dpi.lv/). At that resolution, a 0.5px min-height should always display at least one screen pixel. 

Just grasping at straws here, I suppose I could revise the CSS and change the retina break from 192 dpi to 230 dpi. Is that worth a try? Or maybe Chrome understands 2 dppx better than 192 dpi?

**Comment by ronkok** [comment] 2017-11-17 16:09
@kkiningh This problem is screen-dependent, which makes it hard to test. Do you run KaTeX locally? Would you be willing to test an idea?

If so, open `katex.min.css` , search and replace the string `192dpi` with the string `2dppx`. Then re-test your fraction in Chrome and let me know what you find.

**Comment by ronkok** [comment] 2017-11-18 17:58
Okay, I think I have a plan. We need to change `frac-line` so that it no longer consists of a `bottom-border` but instead consists of an entire span, the way `\rule` works. Then the `min-height` from PR #931 will act more dependably.  There is no such thing as a CSS `border-min-thickness`.

@kevinbarabash If you are planning a bug-fix release, give me a day or two. I'm booked up today, but I think I can turn in a PR by evening tomorrow.

**Comment by akalin** [comment] 2017-11-18 20:17
I've noticed that sometimes vertical lines can also disappear, e.g. the vertical divider in an array environment with `[c|c]`. I'll file a separate bug with a repro case, but do you think that could also be from the same root cause?

**Comment by ronkok** [comment] 2017-11-18 20:53
@akalin  Well, the CSS for `arraycolsep` also works via a span border. I suppose that the same problem could be occurring and that the same adjustment methods could apply. 

I'd like to take one thing at a time. If we can get `frac-line` working dependably, then I'll look at `arraycolsep`.

**Comment by kevinbarabash** [comment] 2017-11-23 21:53
@ronkok sounds good.  I was looking to do an `v0.9.0-alpha2` release sometime this weekend.  Also, switching from `bottom-border` to span height and using `min-height` sounds like a good plan.

**Comment by akalin** [comment] 2017-11-28 07:28
I hate to say it, but it looks like `0.9.0-alpha2` regresses. :( See https://rawgit.com/akalin/60e78169d60908f8111652540f427607/raw/fd7f91f08774a70185c003b8b29f144fb4b65d52/test-0.9.0-alpha2.html , which looks like this to me:
<img width="351" alt="screen shot 2017-11-27 at 11 28 30 pm" src="https://user-images.githubusercontent.com/425576/33307246-b3b6854c-d3ca-11e7-990a-98edc4c924f7.png">

**Comment by ronkok** [comment] 2017-11-29 02:02
Well, that's discouraging. We've had a couple other reports that `0.9.0-alpha2` provided some benefit. I myself have not had any lines disappear on my screen, but I have seen two that are narrower than they were before `0.9.0-alpha2`. So returns are mixed.

@kevinbarabash I think it is time for a belt-and-suspenders approach. Both a border and a full-height span colored by an SVG. They can coexist if I set CSS `box-sizing: border-box;` for `frac-line`. 

What do you think?

**Comment by kevinbarabash** [comment] 2017-11-29 03:04
<img width="423" alt="screen shot 2017-11-28 at 9 49 40 pm" src="https://user-images.githubusercontent.com/1044413/33355889-76bf4b7a-d487-11e7-8917-92c99eba6d0b.png">

The above rendering is from Safari.  The height for each of the fraction lines is the same, the problem (I think), is that we're control the height the fraction line using the enclosing span.  My guess is that the browser tries to quantize the span to some grid and ends up rounding up/down depending on where it lands.

@ronkok maybe we could render a SVG line of the correct thickness within the SVG and then make the enclosing span a bit taller than it needs to be.  Also, the line shouldn't be right near the edge of the SVG.  That should avoid the quantization/clipping the we're seeing currently.

**Comment by ronkok** [comment] 2017-11-29 03:24
@kevinbarabash Your proposal makes a lot of sense. When I was working on PR #670, I found that I had much finer control over SVG geometry than I did over span geometry.

Of course, this means that we'll have to write SVG path geometry on the fly instead of just using `overflow: hidden;` to control line thickness. There might be a tiny performance hit.

I'll write up a PR. This may take a few days. I'm semi-retired these days and I often have some free time but at present I'm spending a lot of time at the office.

**Comment by ronkok** [comment] 2017-11-29 03:33
@akalin If we follow through on @kevinbarabash's proposal, we'll have frac-lines that act like the top lines in square root radicals (as of release 0.8.3). If you see any of those disappear, please let me know.

**Comment by akalin** [comment] 2018-01-15 17:35
0.9.0-beta seems to have completely fixed the problem for me: https://rawgit.com/akalin/60e78169d60908f8111652540f427607/raw/dddea153264adabe863e3a4f6c24c4cd220996dd/test-0.9.0-beta.html

Thanks everyone!

**Comment by ronkok** [comment] 2018-01-15 18:16
@akalin, You're very welcome. I hope that everyone has results this positive.

**Comment by kevinbarabash** [comment] 2018-01-15 20:34
@akalin thanks for verifying that the bug is no longer in the new release.

**Closed** 2018-01-15 20:33 UTC
Labels: bug

**Comment by edemaine** [comment] 2018-04-05 17:26
@jeffmcmahan  #1249 will hopefully fix this.  There's a test page on #1173 that you can check out.

**Comment by ronkok** [comment] 2018-04-05 17:30
Query about npm: When one writes `npm install katex@0.9`, which KaTeX version will that install?

**Comment by jeffmcmahan** [comment] 2018-04-05 17:32
@edemaine - Thanks!
@ronkok - 0.9.0 until a newer patch version is published to npm.

**Comment by ronkok** [comment] 2018-04-05 17:41
If the version is 0.9.0, then something quite odd is happening. In that version, we've gotten reports of frac-lines appearing grey, as in issue #1173, but it should not have an altogether missing line. 

@jeffmcmahan If you can point me to a page, I can take a look.

**Comment by jeffmcmahan** [comment] 2018-04-05 17:58
@ronkok - is a live page essential? I don't have a node server up that I can easily use to post a demo page. Here is a screenshot generated with 0.9.0 installed (using the provided 0.9.0 stylesheet as well):

<a href="https://imgbb.com/"><img src="https://image.ibb.co/gRgHSH/Screen_Shot_2018_04_05_at_1_46_06_PM.png" alt="Screen Shot 2018 04 05 at 1 46 06 PM" border="0" /></a>

LaTeX: `p = 1 - \bigg(\frac{1}{1.8 \times 10^9}\bigg)^{5 \times 10^8}`

Here's the HTML that `katex.renderToString()` produces:

```html
<span class="katex-display"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>p</mi><mo>=</mo><mn>1</mn><mo>−</mo><mo fence="false">(</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>1</mn><mi mathvariant="normal">.</mi><mn>8</mn><mo>×</mo><mn>1</mn><msup><mn>0</mn><mn>9</mn></msup></mrow></mfrac><msup><mo fence="false">)</mo><mrow><mn>5</mn><mo>×</mo><mn>1</mn><msup><mn>0</mn><mn>8</mn></msup></mrow></msup></mrow><annotation encoding="application/x-tex">p = 1 - bigg(frac{1}{1.8 times 10^9}bigg)^{5 times 10^8}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:1.82682em;"></span><span class="strut bottom" style="height:2.77685em;vertical-align:-0.95003em;"></span><span class="base"><span class="mord mathit">p</span><span class="mord rule" style="margin-right:0.2777777777777778em;"></span><span class="mrel">=</span><span class="mord rule" style="margin-right:0.2777777777777778em;"></span><span class="mord">1</span><span class="mord rule" style="margin-right:0.2222222222222222em;"></span><span class="mbin">−</span><span class="mord rule" style="margin-right:0.2222222222222222em;"></span><span class="mord"><span class="delimsizing size3">(</span></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:1.32144em;"><span style="top:-2.314em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">1</span><span class="mord">.</span><span class="mord">8</span><span class="mord rule" style="margin-right:0.2222222222222222em;"></span><span class="mbin">×</span><span class="mord rule" style="margin-right:0.2222222222222222em;"></span><span class="mord">1</span><span class="mord"><span class="mord">0</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.740108em;"><span style="top:-2.9890000000000003em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">9</span></span></span></span></span></span></span></span></span></span><span style="top:-3.15em;"><span class="pstrut" style="height:3em;"></span><span class="stretchy" style="height:0.2em;"><svg width="400em" height="0.2em" viewBox="0preserveAspectRatio=" xminyminslice'=""><path d="M0H400000v40H0zM0H400000v40H0z"></path></svg></span></span><span style="top:-3.677em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">1</span></span></span></span><span class="vlist-s">&#8203;</span></span><span class="vlist-r"><span class="vlist" style="height:0.7693300000000001em;"></span></span></span></span><span class="mclose nulldelimiter"></span></span><span class="mord"><span class="mord"><span class="delimsizing size3">)</span></span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:1.82682em;"><span style="top:-3.9029000000000003em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">5</span><span class="mbin mtight">×</span><span class="mord mtight">1</span><span class="mord mtight"><span class="mord mtight">0</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.8913142857142857em;"><span style="top:-2.931em;margin-right:0.07142857142857144em;"><span class="pstrut" style="height:2.5em;"></span><span class="sizing reset-size3 size1 mtight"><span class="mord mtight">8</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span>
```

**Comment by edemaine** [comment] 2018-04-05 18:38
Maybe you're sanitizing the HTML and removing `<svg>` tags (or some of the subtags)? I had this issue when switching to 0.8.  This reliance will be removed in #1249, but only for frac lines; you should whjte-list SVG tags for other features like `\overrightarrow`.

**Comment by ronkok** [comment] 2018-04-05 18:42
Right. You should white list `<SVG>`, `<path>`, and `<line>`.

**Comment by jeffmcmahan** [comment] 2018-04-05 20:37
Yes, you're right. This was all on me. My HTML parser made a booboo. Sorry!
