### ISSUE TITLE
Incorporate `utensil-site.github.io/available-in-katex/` into official documentation

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1480] opened 2018-07-13 08:34 UTC
http://utensil-site.github.io/available-in-katex/ provides a great list combining http://mathjax.readthedocs.io/en/latest/tex.html#supported-latex-commands, http://www.onemathematicalcat.org/MathJaxDocumentation/TeXSyntax.htm, and https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX. However, it is not actively maintained and currently not working.

I think it'd be nice to clone and incorporate it into official documentation and possibly auto-generate it.

Related: #103, #276, #1138 

CC @utensil

**Comment by ronkok** [comment] 2018-07-13 13:52
It is a great list, but it could be improved. There a are a few functions that it incorrectly flagged as not supported by KaTeX. The root cause was that its test string did not include a closing brace. MathJax accepts that sort of thing, but KaTeX does not.

**Comment by kevinbarabash** [comment] 2018-07-18 01:33
I like the list b/c people can look things up alphabetically.  This is maybe something we could in addition to the existing documentation that's on khan.github.io/KaTeX.

**Closed** 2018-08-02 18:11 UTC

**Comment by utensil** [comment] 2018-08-05 09:04
> http://utensil-site.github.io/available-in-katex/ provides a great list combining http://mathjax.readthedocs.io/en/latest/tex.html#supported-latex-commands, http://www.onemathematicalcat.org/MathJaxDocumentation/TeXSyntax.htm, and https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX. However, it is not actively maintained and currently not working.

It wasn't working because the links to KaTeX css/js somehow became invalid. It's now fixed. Thanks for the heads up. @ylemkimon 

> It is a great list, but it could be improved. There a are a few functions that it incorrectly flagged as not supported by KaTeX. The root cause was that its test string did not include a closing brace. MathJax accepts that sort of thing, but KaTeX does not.

@ronkok , can you name some of these test strings without a closing brace so I can fix them? I failed to spot them still.

**Comment by ylemkimon** [comment] 2018-08-05 09:49
@utensil We support following:
* `\begin` and `\end`
* `\global`, `\def`
* `\left` and `\right`
* `\S`
* `\xtofrom`
* `\xtwoheadleftarrow`
* `\xtwoheadrightarrow`

**Comment by utensil** [comment] 2018-08-05 10:08
> We support following:
> 
> \begin and \end
Fixed.

> \global, \def
Fixed.

> \left and \right
No, I can't get them working

> \S
No, I can't get it working

> \xtofrom
> \xtwoheadleftarrow
> \xtwoheadrightarrow

Fixed.

I've fixed a few other symbols by testing one by one, now there are only 59 symbols/functions failed to render.

**Comment by ylemkimon** [comment] 2018-08-05 10:32
@utensil `\left` and `\right` need to be paired.
