### ISSUE TITLE
The \\ syntax for a new line in block mode throws an error.

### ISSUE THREAD

**Issue by Pomax** [Khan/KaTeX#416] opened 2015-12-16 17:18 UTC
I'm trying to drop-in replace MathJax with KaTeX, and it's throwing an error on the following:
```
<p>\[
  p_1 = some\ point, \\
  p_2 = some\ other\ point, \\
  distance = (p_2 - p_1), \\
  ratio = \frac{percentage}{100}, \\
  new\ point = p_1 + distance \cdot ratio
\]</p>
```
This renders quite correctly using MathJax, but KaTeX throws the following error:
```
KaTeX auto-render: Failed to parse `
          p_1 = some\ point, \\
          p_2 = some\ other\ point, \\
          distance = (p_2 - p_1), \\
          ratio = \frac{percentage}{100}, \\
          new\ point = p_1 + distance \cdot ratio
        ` with  ParseError: KaTeX parse error: Expected 'EOF', got '\\' at position 32: some\ point, \\̲
          p_2
Stack trace:
h@http://khan.github.io/KaTeX/bower_components/katex/dist/katex.min.js:1:6534
[6]</n.prototype.expect@http://khan.github.io/KaTeX/bower_components/katex/dist/katex.min.js:1:7034
[6]</n.prototype.parseInput@http://khan.github.io/KaTeX/bower_components/katex/dist/katex.min.js:1:7256
[6]</n.prototype.parse@http://khan.github.io/KaTeX/bower_components/katex/dist/katex.min.js:1:7138
[21]</a@http://khan.github.io/KaTeX/bower_components/katex/dist/katex.min.js:5:13869
[1]</p@http://khan.github.io/KaTeX/bower_components/katex/dist/katex.min.js:1:998
[1]</i@http://khan.github.io/KaTeX/bower_components/katex/dist/contrib/auto-render.min.js:1:1227
[1]</o@http://khan.github.io/KaTeX/bower_components/katex/dist/contrib/auto-render.min.js:1:1600
[1]</o@http://khan.github.io/KaTeX/bower_components/katex/dist/contrib/auto-render.min.js:1:1741
[1]</o@http://khan.github.io/KaTeX/bower_components/katex/dist/contrib/auto-render.min.js:1:1741
[1]</o@http://khan.github.io/KaTeX/bower_components/katex/dist/contrib/auto-render.min.js:1:1741
[1]</d@http://khan.github.io/KaTeX/bower_components/katex/dist/contrib/auto-render.min.js:1:2203
@file:///C:/Users/Mike/Desktop/A%20Primer%20on%20B%C3%A9zier%20Curves.htm:4373:1
```

**Comment by kevinbarabash** [comment] 2015-12-17 01:38
We don't support `\\` outside of `matrix` and `aligned` environments.  Closing as duplicate of https://github.com/Khan/KaTeX/issues/171.

**Closed by kevinbarabash** 2015-12-17 01:38 UTC

**Comment by Pomax** [comment] 2015-12-17 02:34
Wait, I'm confused; this is perfectly legal LaTeX, why is this not getting supported?
```
\documentclass[12pt]{article}
\setlength{\parindent}{0pt}
\begin{document}
this \\ is \\ a \\ test.
\end{document}
```

**Comment by spicyj** [comment] 2015-12-17 02:39
We don't *currently* support `\\` outside of matrix and aligned. But #171 already tracks supporting it elsewhere so we don't need this issue tracking it too.

(As an aside, KaTeX only replicates math mode so your last example is not relevant – but it's true that `\\` works inside math mode too so we should ideally support it.)

**Comment by Pomax** [comment] 2015-12-17 05:35
ahh, gotcha. thanks

**Comment by spicyj** [comment] 2015-12-17 22:11
No problem, happy to help.
